# Churn Model

In [2]:
#Import the required library
import pandas as pd

In [3]:
# View the content of pandas
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p17',
 '_np_version_under1p18',
 '_testing'

In [4]:
#Importing your data
data = pd.read_csv("Customer-Churn.csv")

In [6]:
# View the first few  rows of your data
data.head(10)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   
5  9305-CDSKC  Female              0      No         No       8          Yes   
6  1452-KIOVK    Male              0      No        Yes      22          Yes   
7  6713-OKOMC  Female              0      No         No      10           No   
8  7892-POOKP  Female              0     Yes         No      28          Yes   
9  6388-TABGU    Male              0      No        Yes      62          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   
5               Yes     Fiber optic             No  ...              Yes   
6               Yes     Fiber optic             No  ...               No   
7  No phone service             DSL            Yes  ...               No   
8               Yes     Fiber optic             No  ...              Yes   
9                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   
5          No         Yes             Yes  Month-to-month              Yes   
6          No         Yes              No  Month-to-month              Yes   
7          No          No              No  Month-to-month               No   
8         Yes         Yes             Yes  Month-to-month              Yes   
9          No          No              No        One year               No   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  
5           Electronic check          99.65         820.5   Yes  
6    Credit card (automatic)          89.10        1949.4    No  
7               Mailed check          29.75         301.9    No  
8           Electronic check         104.80       3046.05   Yes  
9  Bank transfer (automatic)          56.15       3487.95    No  

[10 rows x 21 columns]

In [7]:
#View the last few rows
data.tail(10)

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
7033  9767-FFLEM    Male              0      No         No      38   
7034  0639-TSIQW  Female              0      No         No      67   
7035  8456-QDAVC    Male              0      No         No      19   
7036  7750-EYXWZ  Female              0      No         No      12   
7037  2569-WGERO  Female              0      No         No      72   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
7033          Yes                No     Fiber optic                   No  ...   
7034          Yes               Yes     Fiber optic                  Yes  ...   
7035          Yes                No     Fiber optic                   No  ...   
7036           No  No phone service             DSL                   No  ...   
7037          Yes                No              No  No internet service  ...   
7038          Yes               Yes             DSL                  Yes  ...   
7039          Yes               Yes     Fiber optic                   No  ...   
7040           No  No phone service             DSL                  Yes  ...   
7041          Yes               Yes     Fiber optic                   No  ...   
7042          Yes                No     Fiber optic                  Yes  ...   

         DeviceProtection          TechSupport          StreamingTV  \
7033                   No                   No                   No   
7034                  Yes                   No                  Yes   
7035                   No                   No                  Yes   
7036                  Yes                  Yes                  Yes   
7037  No internet service  No internet service  No internet service   
7038                  Yes                  Yes                  Yes   
7039                  Yes                   No                  Yes   
7040                   No                   No                   No   
7041                   No                   No                   No   
7042                  Yes                  Yes                  Yes   

          StreamingMovies        Contract PaperlessBilling  \
7033                   No  Month-to-month              Yes   
7034                   No  Month-to-month              Yes   
7035                   No  Month-to-month              Yes   
7036                  Yes        One year               No   
7037  No internet service        Two year              Yes   
7038                  Yes        One year              Yes   
7039                  Yes        One year              Yes   
7040                   No  Month-to-month              Yes   
7041                   No  Month-to-month              Yes   
7042                  Yes        Two year              Yes   

                  PaymentMethod MonthlyCharges  TotalCharges Churn  
7033    Credit card (automatic)          69.50       2625.25    No  
7034    Credit card (automatic)         102.95       6886.25   Yes  
7035  Bank transfer (automatic)          78.70        1495.1    No  
7036           Electronic check          60.65         743.3    No  
7037  Bank transfer (automatic)          21.15        1419.4    No  
7038               Mailed check          84.80        1990.5    No  
7039    Credit card (automatic)         103.20        7362.9    No  
7040           Electronic check          29.60        346.45    No  
7041               Mailed check          74.40         306.6   Yes  
7042  Bank transfer (automatic)         105.65        6844.5    No  

[10 rows x 21 columns]

In [8]:
# See the columns in your data
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [9]:
# See the number of rows and columns in your data
data.shape

(7043, 21)

## Feature Extraction

In [10]:
features = data[['gender','Dependents','MonthlyCharges', 'TotalCharges']]


In [11]:
features

gender Dependents  MonthlyCharges TotalCharges
0     Female         No           29.85        29.85
1       Male         No           56.95       1889.5
2       Male         No           53.85       108.15
3       Male         No           42.30      1840.75
4     Female         No           70.70       151.65
...      ...        ...             ...          ...
7038    Male        Yes           84.80       1990.5
7039  Female        Yes          103.20       7362.9
7040  Female        Yes           29.60       346.45
7041    Male         No           74.40        306.6
7042    Male         No          105.65       6844.5

[7043 rows x 4 columns]

In [12]:
# Convert categorical data to numerical
from sklearn.preprocessing import LabelEncoder

In [13]:
# Initialize the LabelEncoder
le = LabelEncoder()

In [14]:
features["gender"] = le.fit_transform(features["gender"])

<ipython-input-14-6c28538fc469>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features["gender"] = le.fit_transform(features["gender"])


In [17]:
features

gender  Dependents  MonthlyCharges TotalCharges
0          0           0           29.85        29.85
1          1           0           56.95       1889.5
2          1           0           53.85       108.15
3          1           0           42.30      1840.75
4          0           0           70.70       151.65
...      ...         ...             ...          ...
7038       1           1           84.80       1990.5
7039       0           1          103.20       7362.9
7040       0           1           29.60       346.45
7041       1           0           74.40        306.6
7042       1           0          105.65       6844.5

[7043 rows x 4 columns]

In [16]:
features["Dependents"] = le.fit_transform(features["Dependents"])

<ipython-input-16-101f17b42c6c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features["Dependents"] = le.fit_transform(features["Dependents"])


In [18]:
target = le.fit_transform(data["Churn"])

In [19]:
target

array([0, 0, 1, ..., 0, 1, 0])

## Split your data in training and testing sets

In [20]:
# Importing the function used for splitting
from sklearn.model_selection import train_test_split

In [21]:
feature_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.3)

In [22]:
feature_train

gender  Dependents  MonthlyCharges TotalCharges
433        1           0           45.40        518.9
585        0           0           85.70         85.7
2019       1           0          104.10      7040.85
5751       0           0           20.25       1029.8
114        0           1           54.60       3423.5
...      ...         ...             ...          ...
4501       0           0           20.70       762.45
3202       1           0           55.25        55.25
1796       0           0           73.65      1642.75
1405       0           0           76.00           76
335        1           1           75.80      5293.95

[4930 rows x 4 columns]

In [23]:
target_train

array([1, 1, 1, ..., 0, 1, 1])

##  Building the model

In [24]:
# Building a classification model using Suport vector machine
# Import the suport the svm library/function

from sklearn.svm import SVC

In [25]:
# Initailize the SVC function
classifier = SVC()

In [28]:
feature_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4930 entries, 433 to 335
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   gender          4930 non-null   int32  
 1   Dependents      4930 non-null   int32  
 2   MonthlyCharges  4930 non-null   float64
 3   TotalCharges    4930 non-null   object 
dtypes: float64(1), int32(2), object(1)
memory usage: 154.1+ KB


In [30]:
# Convert "TotalCharges" to float for training
feature_train["TotalCharges"] = le.fit_transform(feature_train["TotalCharges"])

<ipython-input-30-ebbe357c749b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feature_train["TotalCharges"] = le.fit_transform(feature_train["TotalCharges"])


In [33]:
# Convert "TotalCharges" to float for testing
features_test["TotalCharges"] = le.fit_transform(features_test["TotalCharges"])

<ipython-input-33-f6a66395cfb7>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_test["TotalCharges"] = le.fit_transform(features_test["TotalCharges"])


In [31]:
feature_train

gender  Dependents  MonthlyCharges  TotalCharges
433        1           0           45.40          3099
585        0           0           85.70          4431
2019       1           0          104.10          3950
5751       0           0           20.25            47
114        0           1           54.60          2086
...      ...         ...             ...           ...
4501       0           0           20.70          4164
3202       1           0           55.25          3259
1796       0           0           73.65           794
1405       0           0           76.00          4150
335        1           1           75.80          3160

[4930 rows x 4 columns]

In [32]:
# Training the model
model = classifier.fit(feature_train, target_train)

In [34]:
# Making predictions
prediction = model.predict(features_test)

In [35]:
prediction

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
#Compare actual with predictions using a dictionary
diction = {"Actual  value": target_test, "Predictions": prediction}

In [39]:
diction

{'Actual  value': array([0, 0, 0, ..., 0, 0, 0]),
 'Predictions': array([0, 0, 0, ..., 0, 0, 0])}

In [40]:
# Convert dictionary to a dataframe
pd.DataFrame(diction)

Actual  value  Predictions
0                 0            0
1                 0            0
2                 0            0
3                 0            0
4                 1            0
...             ...          ...
2108              1            0
2109              0            0
2110              0            0
2111              0            0
2112              0            0

[2113 rows x 2 columns]

## Evaluate your model

In [41]:
# Import the function for  accuracy
from sklearn.metrics import accuracy_score

In [42]:
# Check the accuracy of your model
accuracy_score(target_test, prediction)

0.751538097491718

In [43]:
# Using confusion matrix
from sklearn.metrics import confusion_matrix

In [44]:
# Printing the confusion matrix
print(confusion_matrix(target_test, prediction))

[[1588    0]
 [ 525    0]]


In [45]:
##build a model for Logistic regression

from sklearn.linear_model import LogisticRegression

In [46]:
#initialize the class
classifier2 = LogisticRegression()

In [47]:
# build the  model
model2 = classifier2.fit(feature_train,target_train)

In [48]:
# make predictions
prediction2 = model2.predict(features_test)

In [49]:
#Evaluate the accuracy
accuracy_score(target_test, prediction2)

0.7496450544249882

In [50]:
# Printing the confusion matrix
print(confusion_matrix(target_test, prediction2))

[[1584    4]
 [ 525    0]]
