### The assignment sign is "="

# Assigning Values to Variables

In [7]:
age = 24 #integer
name = "John" #string
weight = 80.7 #float
isMale = True
isFemale = False


In [8]:
print(counter)
print(name)
print(weight)
print(isMale)
print(isFemale)

100
John
80.7
True
False


## Multiple assignment

### Python allows you to assign a single value to several variables simultaneously.
### Here, an integer is created with the value 1, and all the three variables are assigned to the same memory location.

In [10]:
a = b = c = 1

In [11]:
print (a)
print (b)
print (c)

1
1
1


### You can also assign multiple objects to multiple variables. For example

In [12]:
name, age, weight = "John", 24, 82.7

In [13]:
print(name, age, weight)

John 24 82.7


# Unpack a list

In [33]:
fruits = ["apple", "orange", "banana"]
x, y, z = fruits
print (x, y, z)

apple orange banana


# 5 Standard Data Types

### Always give examples in tests and exams
### 1. Numbers: int, float, complex

#### Int, or integer, is a whole number, positive or "negative", without decimals, of unlimited length. (e.g., 10, -5, 0)

#### Float, or "floating point number" is a number, positive or negative, containing one or more decimals. (e.g., 3.14, -2.5, 1.0e5)

#### Float can also be scientific numbers with an "e" to indicate the power of 10.  (e.g., 2+3j, -1-0.5j)
##### z = -87.7e100


### 2. Strings: Represents sequences of characters enclosed in single, double or triple quotes.  (e.g., "hello", 'world', "123", """Hi""")
### 3. List: Ordered, mutable (mutable, meaning their elements can be modified after creation. You can add, remove, or change elements using various methods ) collections of elements (e.g., [1, 2, 3], ["apple", "banana", "orange"])
### 4. Tuples: Ordered, immutable (immutable, meaning their elements can't be modified after creation)  collections of elements (e.g., (1, 2, 3), ("apple", "banana", "orange"))
### 5. Dictionary: Unordered key-value pairs (e.g., {"name": "Alice", "age": 30, "city": "New York"})
### 6. Boolean: Represents True or False values (e.g., True, False)

# Python Numbers

#### Number data types store numeric values. Python supports two different numerical types they are: integers and floating point numbers. For example


In [17]:
var1 = 10
var2 = 10.8
print(var1)
print(var2)


10
10.8


# Python Strings

#### Strings are contiguous set of characters that are enclosed in quotation marks either ' or "

In [5]:
print("Strings are contiguous set of characters that \n are enclosed in quotation marks either\" or ' or \"\"\"\"\"\" ")

Strings are contiguous set of characters that 
 are enclosed in quotation marks either" or ' or """""" 


Subsets of strings can be taken using the
slice operator ([ ] and [:] ) with indexes starting at 0 in the
beginning of the string and working their way from -1 to the end.

### The plus (+) sign is the string concatenation operator and the asterisk (*) is the repetition operator.

In [6]:
h = "h"
i = "i"

HI = h + i
print(HI)
print (HI * 4)

hi
hihihihi


In [9]:
greeting = "Hi there"

In [2]:
print(greeting[0])

H


In [3]:
print(greeting[-1])

e


In [4]:
print(greeting[1:4])

i t


In [36]:
print(greeting[0:8])#🎀🎀🎀🎀 7 characters but use 8 exclusive of 8

Hi there


In [41]:
print(greeting[-8:-1]) #greeting[-8:-1] will extract the characters from the 8th position from the end (inclusive) 
#to the 1st position from the end (exclusive) of the string.


Hi ther


### AVOID THIS MISTAKE! NOTE THAT THE STOP INDEX IS EXCLUSIVE OF THE STOP INDEX, SO IT STOPS JUST BEFORE IT WHETHER + OR -

In [40]:
print(greeting[-8:])

Hi there


#### [1:4] will print from the 2 character to the third

In [5]:
print(greeting[1:6])

i the


In [6]:
print(greeting[2:]) #Omitting end index (default is the end of the string)

 there


### To get every third character
#### ie start at the index, jump 2 pick the next, jump 2 pick the next 

In [11]:
print(greeting[::3])
print(greeting[0:8:3])


Htr
Htr


### To get every second character

### To get every second character
#### ie start at the index, jump 1 pick the next, jump 1 pick the next 

In [44]:
print(greeting[::2])

H hr


In [49]:
name7 = "caleb"
print(name7[::3])
print(name7[::2])

ce
clb


In [7]:
print(greeting * 2)

Hi thereHi there


In [9]:
print(greeting + " " + "Jane")

Hi there Jane


# Get the entire string in reverse


In [50]:
print(greeting[::-1])

ereht iH


In [12]:
print(greeting[::-2])

eeti


#### So [::1]
#### will reverse Hi there to ereht iH
#### That means [::2] will reverse and skip every 1 character after the start index here is 0
#### It will be eeti

# Slicing with variables

In [51]:
a = 1
b = 6
print(greeting[a:b])

i the


# Slicing classwork

In [54]:
my_string = "Hello, World!" 
result = my_string[::2]
result = my_string[0::2]
result = my_string[-1::-2]
result = my_string[-1:6:2]# !lo

print(result1 = my_string[::2])
print(result2 = my_string[0::2])
print(result3 = my_string[-1::-2])
print(result4 = my_string[-1:6:2])# !lo


TypeError: 'result1' is an invalid keyword argument for print()

In [55]:
my_string = "Hello, World!" 

# Performing string slicing and storing results in variables
result1 = my_string[::2]      # Takes every 2nd character, starting from the beginning
result2 = my_string[0::2]     # Also takes every 2nd character, starting from index 0 (same as above)
result3 = my_string[-1::-2]   # Takes every 2nd character in reverse order, starting from the last character
result4 = my_string[-1:6:2]   # Takes every 2nd character starting from the last character up to index 6 (not inclusive)

# Printing the results
print("result1 =", result1)
print("result2 =", result2)
print("result3 =", result3)
print("result4 =", result4)  # Expected output is '!lo'


result1 = Hlo ol!
result2 = Hlo ol!
result3 = !lo olH
result4 = 


result4 didn't print because it expects every stop character to come after the start and not the start character after the stop 

# Variables casting

### This is used to specify the data type

In [26]:
x = str(3)
y = int(3.0)
z= float(3)

In [29]:
print (x)
print (y)
print (z)

3
3
3.0


# Getting the type of the variable

In [30]:
type(x)

str

In [31]:
print(type(x))

<class 'str'>


# Arithmetic Operators   + - / * % < > <= >=

## 4 + 5 where 4 and 5 are the operands and + is the operators

In [14]:
num1 = 20
num2 = 5
num3 = 3

In [20]:
num1==num2

False

In [13]:
print(num1 + num2)

25


In [11]:
aaaaaa= 5
bbbbb= 10
print(aaaaaa / bbbbb )

0.5


In [14]:
print(num1 - num2)

15


In [15]:
print(num1 / num2)

4.0


In [16]:
print(int(num1 / num2))

4


In [17]:
print(num1 / num3)

6.666666666666667


In [18]:
print(num1 // num3)

6


#### // is the operator for integer division in Python.
#### It divides num1 by num3 and returns the quotient as an integer (ie the whole number part), discarding any remainder.

In [21]:
print(num1 % num3) #ie the remainder of 20/3

2


#### How does % work? Another way to say it is, “X divided by Y with J remaining.” For example, “100 divided by 16 with 4 remaining.” The result of % is the J part, or the remaining part.

In [16]:
print(num2 ** num3) # ie 5 raised to the power of 3

125


### What is the order of operations?
###  PEMDAS which stands for Parentheses Exponents Multiplication Division Addition Subtraction. 

### That’s the order Python follows as well. The mistake people make with PEMDAS is to think this is a strict order, as in “Do P, then E, then M, then D, then A, then S.” 

### The actual order is you do the multiplication and division (M&D) in one step, from left to right, then you do the addition and subtraction in one step from left to right. 

### So, you could rewrite PEMDAS as PE(M&D)(A&S)


# What is the difference between = (single-equal) and == (double- equal)? 

### The = (single-equal) assigns the value on the right to the left. It is called the assignment operator
### The == (double-equal) tests whether two things have the same value. It is called the equal to comparison operator

# Comparison operators == != < > <= >=

In [23]:
num4 = 4
num5 = 5
num6 = 4

In [24]:
num4 == num5

False

In [25]:
print(num4 == num5)

False


In [26]:
print(num4 == num6)

True


In [27]:
print(num4 > num6)

False


In [28]:
print(num4 >= num6)

True


In [29]:
print(num4 < num5)

True


In [30]:
print(num5 <= num6)

False


In [31]:
print(num4 != num6)

False


In [33]:
print(num4 != num5) # != means "not equal to"

True


# Identifiers

#### Identifier is the name given to entities like variable, function, class etc. in python.
#### E.g. myname = “Charis”. The identifier myname is a variable name with the value “Charis” assigned to it.


## Naming rules for Identifiers

#### 1. Identifiers can contain any small letter (a .. z) or capital letter (A .. Z), underscore ( _ ), digit (0...9).
#### 2. An identifier can be any combination of the above but must not start with a digit.
#### E.g. Kazeem1 is valid but 1Kazeem is not valid
#### E.g. _123Kazeem is valid but 123Kazeem is not valid

#### 3. Identifiers are letter case sensitive
#### E.g. an identifier named Kazeem is different from another named kazeem
#### 4. Special symbols like !,&, @, # etc cannot be used in our identifier E.g. myname!  = “Kazeem” is invalid


#### 5. Identifiers cannot use the language’s own keywords (also called reserved words)

#### False	class	finally	is	return
#### None	continue	for	lambda	try
#### True	def	from	nonlocal	while
#### and	del	global	not	with
#### as	elif	if	or	yield
#### assert	else	import	pass	 
#### break	except	in	raise	 

## The convention is that the first word always begin with a small letter and each of the other words begin with capital letter.

### Camel case ie camelCase
#### myClassList
#### averageHeight


# Python Lists

In [5]:
yes = 'Hello World!'
print (yes) # Prints complete string
print (yes[0]) # Prints first character of the string
print (yes[2:5]) # Prints characters starting from 3rd to 5th
print (yes[2:]) # Prints string starting from 3rd character
print (yes * 2) # Prints string two times
print (yes + "TEST") # Prints concatenated string

Hello World!
H
llo
llo World!
Hello World!Hello World!
Hello World!TEST


In [59]:
K = 500
print(K)
t  = "james kaka"
print(t[2:])
print(t[2:5])
print(t[0:5])
print(t[-5:])


500
mes kaka
mes
james
 kaka


In [19]:
my1_string = "Hello, World!"
print(my1_string[-6:-1])

World


In [21]:
my1_string = "Hello, World!"
print(my1_string[-6:1])

In [27]:
my2_string = "Helloo"
print(my2_string[-6:1]) #it will print just the 1st because -6 and 1 are the same unlike the others, the stop must come after the start not before

H


In [23]:
my1_string = "Hello, World!"
print(my1_string[-1:-1])

In [28]:
my1_string = "Hello, World!"
print(my1_string[-1:2])

In [32]:
my1_string = "Hello, World!"
print(my1_string[-1:4])

# Home Work

In [33]:
theString = "Hello, World!"
print(theString[::2])

Hlo ol!


In [34]:
theString = "Hello, World!"
print(theString[0::2])

Hlo ol!


In [40]:
theString = "Hello, World!"
print(theString[-1::-2])#-1 is from the back ie  !dlroW ,olleH then with a -2 step we have !lo olH

!lo olH


In [48]:
theString = "Hello, World!"
print(theString[-1:6:2])#!lo NO ACTUALLY, WHEN THE STOP COMES BEFORE THE START, FOR IT TO WORK, IT MUST BE NEGATIVE INDEX LIKE BELOW

In [49]:
theString = "Hello, World!"
print(theString[-1:6:-2])#!lo

!lo


In [51]:
t = 'james kaka'
print(t[2:]) #mes kaka
print(t[2:5]) #mes
print(t[0:5]) #james w/o the space
print(t[-5:]) # kaka w the space

mes kaka
mes
james
 kaka


# Lists

In [60]:
list1 = ['physics', 'chemistry', 1997, 2000]
list2 = [1, 2, 3, 4, 5 ]
list3 = ["a", "b", "c", "d"]


In [87]:
dd = [4,5,6,4,5,6,7,1,3,4]
print(dd[1:6:2]) # [5,4,6]
print(dd[-1::-3])# [4,7,4,4]
print(dd[1::3])# [5,5,1]
print(dd[-1::3])# [4,7,4,4]

[5, 4, 6]
[4, 7, 4, 4]
[5, 5, 1]
[4]


# VERY IMPORTANT FOR THE ABOVE

Let's analyze each of the slicing operations in your code to understand how they work and why the last result is not as expected.

### List `dd`:
```python
dd = [4, 5, 6, 4, 5, 6, 7, 1, 3, 4]
```
This list contains 10 elements: `[4, 5, 6, 4, 5, 6, 7, 1, 3, 4]`.

### 1. `print(dd[1:6:2])`
This is slicing the list with the syntax `dd[start:end:step]`, meaning:
- Start at index `1`
- Stop before index `6`
- Step by `2`

Indexes in `dd`:
```
Index:  0  1  2  3  4  5  6  7  8  9
List:  [4, 5, 6, 4, 5, 6, 7, 1, 3, 4]
```

So, starting at index `1` (which is `5`), then stepping by `2` gives us the elements at indexes `1`, `3`, and `5`. That would be:
```
dd[1] = 5
dd[3] = 4
dd[5] = 6
```

Output:
```
[5, 4, 6]
```

### 2. `print(dd[-1::-3])`
This is slicing the list with the syntax `dd[start:end:step]`:
- Start at index `-1` (which is the last element, `4`)
- Go backwards (since the step is `-3`) until the beginning of the list (end is not specified, so default is `None`).

Indexes in reverse:
```
Index:   9   8   7   6   5   4   3   2   1   0
List:   [4,  3,  1,  7,  6,  5,  4,  6,  5,  4]
```

Starting from the last element (`4` at index `9`), and stepping by `-3` gives us the elements at indexes `9`, `6`, `3`, and `0`:
```
dd[9] = 4
dd[6] = 7
dd[3] = 4
dd[0] = 4
```

Output:
```
[4, 7, 4, 4]
```

### 3. `print(dd[1::3])`
This is slicing the list with the syntax `dd[start:end:step]`:
- Start at index `1` (which is `5`)
- Go until the end of the list (no end specified)
- Step by `3`

Indexes:
```
Index:  0  1  2  3  4  5  6  7  8  9
List:  [4, 5, 6, 4, 5, 6, 7, 1, 3, 4]
```

Starting from index `1` (which is `5`), and stepping by `3` gives us the elements at indexes `1`, `4`, and `7`:
```
dd[1] = 5
dd[4] = 5
dd[7] = 1
```

Output:
```
[5, 5, 1]
```

### 4. `print(dd[-1::3])`
This is slicing the list with the syntax `dd[start:end:step]`:
- Start at index `-1` (which is the last element, `4`)
- Go forward by `3` (since the step is positive)

Now, here is where the issue lies. When you start at `-1` (the last element) and step forward by `3`, **there are no more elements beyond the last one**. The only element you have is the one at index `-1` (the last element), so you only get the single element `4`.

There are no additional elements to step forward to.

Output:
```
[4]
```

### **Why Not `[4, 7, 4, 4]`?**
The difference between `dd[-1::-3]` (where you're stepping backwards) and `dd[-1::3]` (where you're stepping forwards) is that when you slice backwards (`-3`), you start at the last element and go back through the list. But when you slice forwards (`3`), you're starting at the last element and trying to move beyond it—which isn't possible because there are no more elements in the list.

### Summary of Outputs:
```python
print(dd[1:6:2])   # Output: [5, 4, 6]
print(dd[-1::-3])  # Output: [4, 7, 4, 4]
print(dd[1::3])    # Output: [5, 5, 1]
print(dd[-1::3])   # Output: [4]
```

### Accessing Values in Lists


In [62]:
print(list1[0])

physics


In [63]:
print(list1[3])

2000


In [64]:
print(list1[0:2])

['physics', 'chemistry']


In [65]:
print(list1[-3:])

['chemistry', 1997, 2000]


In [66]:
print(list1[-4:])

['physics', 'chemistry', 1997, 2000]


In [67]:
print(list1[0:5])

['physics', 'chemistry', 1997, 2000]


In [68]:
print(list1[0:4])

['physics', 'chemistry', 1997, 2000]


### Updating Lists

In [69]:
list1[3] = 2001
print(list1)

['physics', 'chemistry', 1997, 2001]


### Deleting elements in a list
#### To remove a list element, you can use either the del statement if you know exactly which element(s) you are deleting

In [52]:
toDeleteList = ["the", "at" "there", "you"]
del toDeleteList[2]
print(toDeleteList)

['the', 'atthere']


#### Notice what happened because the comma wasn't there

In [53]:
toDeleteList2 = ["the", "at", "there", "you"]
del toDeleteList2[2]
print(toDeleteList2)

['the', 'at', 'you']


## Basic list operations

In [55]:
V = [1,2,3]
U = [4,5,6]
print(U+V)
print(V+U)

[4, 5, 6, 1, 2, 3]
[1, 2, 3, 4, 5, 6]


In [135]:
languages = ['Python', 'Java', 'C++', 'French', 'C']
languages.pop(3)
print(languages)

['Python', 'Java', 'C++', 'C']


### Adding Elements to a Python List

In [70]:
list1.append("John")

In [71]:
print (list1)

['physics', 'chemistry', 1997, 2001, 'John']


### Adding Elements to a Python List

In [75]:
del list1[-1]

In [76]:
print list1

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (889844391.py, line 1)

In [77]:
print (list1)

['physics', 'chemistry', 1997, 2001]


In [78]:
list4 = [11, 12]

In [79]:
print (list2 + list4)

[1, 2, 3, 4, 5, 11, 12]


In [80]:
greetList = ["Hi"]

In [81]:
greetList*4

['Hi', 'Hi', 'Hi', 'Hi']

## Append vs Extend

#### append() and extend() are both methods used to add elements to a list in Python, but they serve different purposes:

#### append()

#### Adds a single element to the end of a list.
#### Takes a single element as an argument.


In [82]:
my_list4 = [1, 2, 3]
my_list4.append(4)
print(my_list4)

[1, 2, 3, 4]


#### extend()

#### Adds multiple elements from another list.
#### Takes an iterable as an argument.

In [60]:
my_list5 = [1, 2, 3]
my_list5.extend([4, 5])
print(my_list5)


[1, 2, 3, 4, 5]


In [61]:
my_tuple5 = (1, 2, 3)
my_tuple5.extend((4, 5))
print(my_tuple5)

AttributeError: 'tuple' object has no attribute 'extend'

So tuples can't be extended. Remember it's imutable!

### INSERT

#### insert() is another method used to add elements to a list in Python. Unlike append() and extend(), which always add elements to the end of the list, insert() allows you to add an element at a specific index within the list. 
#### list.insert(index, element)
#### The insert() method is used to add an element at a specific position in a list.
#### The first argument (1 in this case) is the index where you want to insert the new element.
#### The second argument (0 in this case) is the value you want to insert at that position.


In [63]:
my_list7 = [4, 2, 3]
my_list7.insert(1, 0)
print(my_list7)

[4, 0, 2, 3]


### Get the length of a list
#### len() is a built-in function in Python that returns the number of elements in a sequence (like a string, list, or tuple). It's a useful tool for determining the size or length of a container.
#### len(object)

In [86]:
# String
my_string0 = "Hello, world!"
length = len(my_string0)
print(length)  # Output: 13

# List
my_list0 = [1, 2, 3, 4, 5]
length = len(my_list0)
print(length)  # Output: 5

# Tuple
my_tuple0 = (10, 20, 30)
length = len(my_tuple0)
print(length)  # Output: 3

13
5
3


## Sorting

In [70]:
aa = [2, 1, 3, 5, 4]
bb = [2, 1, 3, 5, 4]
xc = [3,5,4,2,1,0,9]

aa.sort()  # Sort the list in ascending order
bb.reverse()  # Reverse the order of elements
cc = xc.sort()
dd = xc.reverse() #cc and dd will return none so to sort just do directly liek aa and bb where after you have the list you do aa.sort()

In [69]:
print(aa)
print(bb)
print(cc)
print(dd)

[1, 2, 3, 4, 5]
[4, 5, 3, 1, 2]
None
None


## Sorting in desc
#### The sort() method sorts the list in place (modifying the original list) and allows you to sort in descending order by specifying reverse=True.

In [93]:
L = [4, 2, 9, 1, 7]
L.sort(reverse = True)
print (L)

[9, 7, 4, 2, 1]


## To sort in desc No actually reverse just reverses the list w/o any form of sorting look up

In [92]:
T = [4, 2, 9, 1, 7]
T.reverse()
print(T)# It doesn't sort in desc!

[7, 1, 9, 2, 4]


In [93]:
C = [3, 1, 4, 1, 5, 9, 2, 6, 5]
print(C.sort())# don't do this

None


In [71]:
C = [3, 1, 4, 1, 5, 9, 2, 6, 5]
C.sort()
# so you're basically sorting first then printing not to assign th esorted to another variable o

In [95]:
print (C)

[1, 1, 2, 3, 4, 5, 5, 6, 9]


In [96]:
C.reverse()

In [97]:
print(C)

[9, 6, 5, 5, 4, 3, 2, 1, 1]


## Finding Elements

In [77]:
k = [1, 2, 3, 4, 5,4,3,9,10]
elementToFind = 3
elementAtIndex = k.index(elementToFind) 
print(elementAtIndex)
print("Found at index ",elementAtIndex)

2
Found at index  2


OR

In [75]:
# Find the index of the first occurrence of 3
k = [1, 2, 3, 4, 5,4,3,9,10]
threeAtIndex = k.index(3)
print(threeAtIndex)

2


## Count the number of occurrences of

In [105]:
e = [2, 3, 4, 4, 3, 1, 1]
count1 = e.count(1)
print(count1)

2


In [108]:
j = ['physics', 'chemistry', 1997, 2000]
j[4] = 3000
print(j[4])



IndexError: list assignment index out of range

In [110]:
j = ['physics', 'chemistry', 1997, 2000]
j[3] = 3000
print(j[3])
print(j)


3000
['physics', 'chemistry', 1997, 3000]


In [78]:
p = ['physics', 'chemistry', 1997, 2000]
p = p*p
print(p)

TypeError: can't multiply sequence by non-int of type 'list'

In [79]:
p = ['physics', 'chemistry', 1997, 2000]
p = p*2
print(p)

['physics', 'chemistry', 1997, 2000, 'physics', 'chemistry', 1997, 2000]


In [111]:
s = [1,3,4,5]*2
print(s)

[1, 3, 4, 5, 1, 3, 4, 5]


In [82]:
aaa = ['physics', 'chemistry', 1997, 2000]
aaa[7] = ['j']
print(aaa)

IndexError: list assignment index out of range

In [83]:
po = [1,3,4,5]*2
print(po[8])

IndexError: list index out of range

In [85]:
Po = [1,3,4,5]*2
del (Po[8])

IndexError: list assignment index out of range

In [84]:
po = [1,3,4,5]*2
print(po)

[1, 3, 4, 5, 1, 3, 4, 5]


In [113]:
# To multiply each element by 2, you can use a list comprehension:
d = [1,3,4,5]
d = [element * 2 for element in d]
print(d)

[2, 6, 8, 10]


In [114]:
l = [4,5,6,4,5,6,7,1,3,4]
print(l[1:6:2]) 


[5, 4, 6]


#### L[1:6] specifies the range of elements to extract, starting from index 1 (the second element) and ending at index 5 (exclusive)
#### :2 specifies the step size, meaning it will skip every other element.


In [115]:
print(l[-1::-3])


[4, 7, 4, 4]


#### L[-1:]: This specifies the range of elements to extract, starting from the last element (index -1) and going to the end of the list.
#### :-3: This specifies the step size, meaning it will skip every two elements in reverse order.

# Index of Last occurence

#### You can reverse the list and find the first occurrence from the end, then adjust the index:

In [107]:
J =[4,5,6,7,8,4,0]

lastIndexof4 = len(J) - 1 - J[::-1].index(4)
# This len(J) - 1 is trying to get index because index is len-1
print(lastIndexof4)

5


In short, len(J) - 1 is used to get the last index of the list because the index of the last element is always length of the list - 1.

So the line:

python
Copy code
lastIndexof4 = len(J) - 1 - J[::-1].index(4)
works by:

J[::-1]: Reversing the list.
.index(4): Finding the first occurrence of 4 in the reversed list.
len(J) - 1: Refers to the last index of the original list.
len(J) - 1 - reversed_index: Converts the index from the reversed list back to the index in the original list.
This finds the last occurrence of 4 in the original list J.

Output:

python
Copy code
5

In [117]:
m =[4,5,6,7,8,4,0]


In [119]:
m = [4, 5, 6, 7, 8, 4, 0]

# Finding the index of the last occurrence of 4
last_index = len(m) - 1 - m[::-1].index(4)

print("The last occurrence of 4 is at index:", last_index)

The last occurrence of 4 is at index: 5


#### Explanation:
#### m[::-1]: This reverses the list.
#### m[::-1].index(4): This finds the index of the first occurrence of 4 in the reversed list.
#### The expression len(m) - 1 gives you the index of the last element in the list m.
#### len(m) - 1 - ...: This converts the reversed index back to the original index by subtracting the reversed index from the total length of the list minus 1.
#### So, this will output the index of the last occurrence of 4 in the list m.

Step-by-Step Explanation:

Reversing the List:
m[::-1] reverses the list m. The reversed list becomes: [0, 4, 8, 7, 6, 5, 4]

Finding the First Occurrence of 4 in the Reversed List:
m[::-1].index(4) finds the first occurrence of 4 in the reversed list. The first 4 in this reversed list is at index 1.

Converting the Index Back to the Original List:
To convert this index from the reversed list back to the original list:

len(m) = 7 (since m has 7 elements).
The index of the last element in the original list is len(m) - 1 = 6.

To find the correct index of the last occurrence of 4 in the original list, we use:

len(m) - 1 - m[::-1].index(4)


In [1]:
n = [4, 5, 6, 7, 8, 4, 0]
four = 4
n.reverse()
index = n.index(four)
print(len(n)-index)

6


In [2]:
p = [4, 5, 6, 7, 8, 4, 0]
p.reverse() #To reverse the list
index4 = p.index(4)
print(len(p)-index4)

6


In [1]:
Joy = "Hello World"

In [2]:
print(Joy[-6:-1])

 Worl


In [132]:
Things = ['physics', 'chemistry', 1997, 2000]
del Things[2]
print(Things)

['physics', 'chemistry', 2000]


In [133]:
Things[4]= 3000

IndexError: list assignment index out of range

In [134]:
has = [1,3,4,5]*2
print(has[8])

IndexError: list index out of range

# Practice all exercises in lecture 6

## AVG, MIN & MAX

In [1]:
james = 20
james = 20
Biodun = 56
Kaka = 76
Jumoke = 30
Bolaji = 23
Chuckwu = 40

I'd get back to this

# Python Tuples

Tuples are sequences, just like lists. 
The main difference between the tuples and the lists is that the tuples cannot bechanged unlike lists.

Notes:
1. Tuples are immutable. To modify,
change to list – list(tuple) – and then
change back to tuple – tuple(list).
2. len(tuple), min(tuple), max(tuple)
4. del removes an entry

# please try these out

In [110]:
tup1 = ('physics', 'chemistry', 1997, 2000)
tup2 = (1, 2, 3, 4, 5 )

print(tup1[2])
print(tup2[0:2])

1997
(1, 2)


In [114]:
tup3 = tup1 + tup2
print(tup3)

('physics', 'chemistry', 1997, 2000, 1, 2, 3, 4, 5)


In [115]:
print(tup3)

('physics', 'chemistry', 1997, 2000, 1, 2, 3, 4, 5)


In [116]:
del tup3

In [117]:
print (tup3)

NameError: name 'tup3' is not defined

In [119]:
print(tup2 * 4)

(1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5)


In [129]:
Tup1 = (12, 34.56,45)
Tup1[0] = 13

TypeError: 'tuple' object does not support item assignment

In [130]:
print(Tup1[-1])

45


# Dictionaries

Each key is separated from its value by a
colon (:), the items are separated by
commas, and the whole thing is
enclosed in curly braces.

In [121]:
dict = {"Name":"Charis Oneyemi", "Program":"MSc Data Science", "Age":23, "Class":"First"}
print(dict["Name"])
print(dict["Program"])
print(dict["Class"])

Charis Oneyemi
MSc Data Science
First


## Updating dictionary

In [122]:
dict["University"] = "Pan Atlantic University"
dict["Internship"] = "Google"

print(dict)

{'Name': 'Charis Oneyemi', 'Program': 'MSc Data Science', 'Age': 23, 'Class': 'First', 'University': 'Pan Atlantic University', 'Internship': 'Google'}


In [124]:
dict["University"] = "Pan Atlantic University (PAU)" #we updated the already creted one here
print(dict)

{'Name': 'Charis Oneyemi', 'Program': 'MSc Data Science', 'Age': 23, 'Class': 'First', 'University': 'Pan Atlantic University (PAU)', 'Internship': 'Google'}


In [125]:
dict2 = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
del dict2['Name'] # remove entry with key 'Name'
dict3 = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
del dict3 

In [126]:
print (dict2)

{'Age': 7, 'Class': 'First'}


In [127]:
print (dict3)

NameError: name 'dict3' is not defined

### Property of Dictionary key

More than one entry per key is not allowed.
This means no duplicate key is allowed.
When duplicate keys are encountered
during assignment, the last assignment
wins.

## Conditions and Iterations


#### Boolean expressions evaluate to True or False
#### Can be used for decision making.
#### Keywords include: 
#### if 
#### else 
#### elif (this is equivalent to else if combined)


In [ ]:
numberA = 10
if numberA > 20
    print(f"{numberA} is greater than ")

# Conditional Statements

## If statements

In [1]:
sample_num = 10
if (sample_num ==10)
    print("correct")
else:
    print("incorrect")

SyntaxError: expected ':' (757218588.py, line 2)

### N/B: You need to put a colon after your if(): not just if()

In [2]:
sample_num = 10
if (sample_num ==10):
    print("correct")
else:
    print("incorrect")

correct


## Collecting input

In [4]:
age = int(input("Enter your age: "))
if (age >= 20):
    print("Access")
else:
    print("Access denied")

Enter your age: 12
Access denied


#### Note when you collect something from an input it saves as string so you have to convert to int with int()

In [11]:
numZ = input("Enter your age: ")
print(type(numZ))


Enter your age: 23
<class 'str'>


### So it is string now but to change it to int look below

In [13]:
numY = int(input("Enter your age: "))

print(type(numY))


Enter your age: 23
<class 'int'>


In [9]:
print(type(age1))

<class 'int'>


In [14]:
age1 = int(input("Enter your age: "))
if (age1 >= 20):
    print("Access")
elif (age1 >=18 AND age <20):
    print("Minimal Access Granted")
else:
    print("Access denied")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (768477595.py, line 4)

#### Note: When using AND, It is and not AND

In [8]:
age1 = int(input("Enter your age: "))
if (age1 >= 20):
    print("Access")
elif (age1 >=18 and age <20):
    print("Minimal Access Granted")
else:
    print("Access denied")

Enter your age: 19
Minimal Access Granted


#### The If returns true or fales. If true print the if and if false print the else

## FOR LOOP

In [16]:
numbers1 = [1,2,3,4,5,6,7,8,9,10]

for num in numbers1:
    print (num)

1
2
3
4
5
6
7
8
9
10


In [19]:
BagOfBalls = ["ball 1 \n", "ball 2 \n", "ball 3 \n"]

for ball in BagOfBalls:
    print (ball)

ball 1 

ball 2 

ball 3 



#### CHECK OUT NESTED FOR LOOPS

In [26]:
BagOfBalls = ["ball 1 \n", "ball 2 \n", "ball 3 \n"]

for ball in BagOfBalls:
    print ("Current ball: ", ball)
    print("Ciao Bella\n")# This is in the for loop so it will print everytime it prints the ball.

Current ball:  ball 1 

Ciao Bella

Current ball:  ball 2 

Ciao Bella

Current ball:  ball 3 

Ciao Bella



In [25]:
BagOfBalls = ["ball 1 \n", "ball 2 \n", "ball 3 \n"]

for ball in BagOfBalls:
    print ("Current ball: ", ball)
print("Ciao Bella\n")# This is out of the for loop so it will only print once.

Current ball:  ball 1 

Current ball:  ball 2 

Current ball:  ball 3 

Ciao Bella



### Let's say you want to sum the numbers in the list

In [30]:
numbers1 = [1,2,3,4,5,6,7,8,9,10]

for num in numbers1:
    num += num
    print (num)

2
4
6
8
10
12
14
16
18
20


### Let's say you want to sum the numbers in the list

In [36]:
numbers1 = [1,2,3,4,5,6,7,8,9,10]
SumOfNumbers = 0 #initializing our sum to 0 ie empty which will store the sum
for (num in numbers1):
    SumOfNumbers += num
    print(SumOfNumbers)

SyntaxError: invalid syntax (288803493.py, line 3)

### The issue is that in for loop we dont have () like for () that's for if()

In [37]:
numbers1 = [1,2,3,4,5,6,7,8,9,10]
SumOfNumbers = 0 #initializing our sum to 0 ie empty which will store the sum
for num in numbers1:
    SumOfNumbers += num
    print(SumOfNumbers)

1
3
6
10
15
21
28
36
45
55


In [ ]:
numbers1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

total_sum = 0  # Initialize a variable to store the sum

for num in numbers1:
    total_sum += num  # Add each number to total_sum

print("The total sum is:", total_sum)

In [33]:
for numA in range (0,10): #ie 0-9
    print(numA)

0
1
2
3
4
5
6
7
8
9


In [39]:
for numA in range (0,10,2): #ie even numbers starting with 0
    print(numA)

0
2
4
6
8


In [41]:
myList = [2,4,5,6,7,8,34]
for num in range (0,6,2):# 0 to 6 is 2,4,5,6,7,8 (ie counting index based 5 but counting regularly the 6th element)
    print(myList[num])

2
5
7


In [42]:
myList = [2,4,5,6,7,8,34]
for num in range (0,6,2):# 
    print(myList)

[2, 4, 5, 6, 7, 8, 34]
[2, 4, 5, 6, 7, 8, 34]
[2, 4, 5, 6, 7, 8, 34]


In [44]:
myList = [2,4,5,6,7,8,34]
for num in range (0,6,2):# ie, it ignores the myList and just executes for num in range (0,6,2) ie the range of numbers 0 to 5 ignoring the 6th skipping 2
    print(num)

0
2
4


# Using a list of numbers of your choice, write a program that collects all odd numbers into one list and all even numbers list


In [45]:
EvenOddList = [12, 37, 58, 21, 64, 43, 76, 19, 82, 55]

for even in EvenOddList:
    if (EvenOddList % 2 = 0):
        print(f"The even numbers in the list are: {even}")
for odd in EvenOddList:
    if (EvenOddList % 2 != 0):
        print(f"The odd numbers in the list are: {odd}")

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (438701509.py, line 4)

In [46]:
EvenOddList = [12, 37, 58, 21, 64, 43, 76, 19, 82, 55]

for even in EvenOddList:
    if (EvenOddList % 2 == 0):
        print(f"The even numbers in the list are: {even}")
for odd in EvenOddList:
    if (EvenOddList % 2 != 0):
        print(f"The odd numbers in the list are: {odd}")

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [47]:
EvenOddList = [12, 37, 58, 21, 64, 43, 76, 19, 82, 55]

for aNumber in EvenOddList:
    if (EvenOddList % 2 == 0):
        print(f"The even numbers in the list are: {aNumber}")
    else:
        print(f"The odd numbers in the list are: {aNumber}")

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [49]:
EvenOddList = [12, 37, 58, 21, 64, 43, 76, 19, 82, 55]

for TheNumber in EvenOddList:
    if (TheNumber % 2 == 0):
        print(f"The even numbers in the list are: {TheNumber}")
    else:
        print(f"The odd numbers in the list are: {TheNumber}")

The even numbers in the list are: 12
The odd numbers in the list are: 37
The even numbers in the list are: 58
The odd numbers in the list are: 21
The even numbers in the list are: 64
The odd numbers in the list are: 43
The even numbers in the list are: 76
The odd numbers in the list are: 19
The even numbers in the list are: 82
The odd numbers in the list are: 55


In [4]:
EvenOddList = [12, 37, 58, 21, 64, 43, 76, 19, 82, 55]

evenList = []
oddList = []

for TheNumber in EvenOddList:
    if (TheNumber % 2 == 0):
        evenList.append(TheNumber)
    else:
        oddList.append(TheNumber)
        
print(f"The list with Even numbers is: {evenList}")
print(f"The list with Odd numbers is: {oddList}\n")


sumOfEven = 0
sumOfOdd = 0

for num in evenList:
    sumOfEven+= num

for num in oddList:
    sumOfOdd+= num

print(f"The sum of Even numbers is: {sumOfEven}")
print(f"The sum of Odd numbers is: {sumOfOdd}")





The list with Even numbers is: [12, 58, 64, 76, 82]
The list with Odd numbers is: [37, 21, 43, 19, 55]

The sum of Even numbers is: 292
The sum of Odd numbers is: 175


# Functions

In [206]:
def calculate_area(length, breadth): #calculate_area is the identifier or function name and length, breadth are the parameters
    area = length * breadth #how to find the area
    return area

length = 2
breadth = 4

area = calculate_area(length,breadth) 
#before answer = calculate_area(l,b) will execute, it will go to the def function the returns with the formula which gives the answer
print(f"the area is {area}")



the area is 8


In [17]:
def calculate_area(length, breadth): #calculate_area is the identifier or function name and length, breadth are the parameters
    area = length * breadth #how to find the area
    return area

l = 2
b = 4

area = calculate_area(length,breadth) 
#before answer = calculate_area(l,b) will execute, it will go to the def function the returns with the formula which gives the answer
print(f"Area is {area}")



Area is 8


The might ask line of execution.
confirm with chag

### Another

In [14]:
def calculate_area(length, breadth): #calculate_area is the identifier or function name and length, breadth are the parameters
    area = length * breadth #how to find the area
    return area

length = 2
breadth = 4

area = calculate_area(length,breadth) 

print(f"The area is {calculate_area(length,breadth) }")

The area is 8


### What I like

In [205]:
def calculate_area(length, breadth): #calculate_area is the identifier or function name and length, breadth are the parameters
    area = length * breadth #how to find the area
    return (f"The area is {area}")
print(calculate_area(2,4))

The area is 8


## PALINDROME
#### A word that if you reverse, it will still be the same like MADAM

In [25]:
def palindrome_checker(the_word):
    reverse_the_word = the_word[::-1]
    
    if reverse_the_word == the_word:
        return "It is a Palindrome"
    else:
        return "It is not a Palindrome"
the_word = "madam"


answer = palindrome_checker(the_word)
print(answer)

It is a Palindrome


In [221]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
def palindrome_checker(the_word):
    reverse_the_word = the_word[::1]
    if reverse_the_word == the_word:
        print("It is a palindrome")
    else:
        print("It is not a palindrome")
answer palindro

In [26]:
email = "charisoneyemi@gmail.com"
at = "@"

if at in email:
    print("It is an email")
else:
    print("It is not an email")

It is an email


In [31]:
def checkEmailValidity (email):
    if at and dotCom in email:
        print("It is an email")
    else:
        print("It is not an email")
email = "charisoneyemi@gmail.com"
at = "@"
dotCom =".com"

answer = checkEmailValidity (email)
print(answer)

It is an email
None


##### why none and none not in bottom

In [30]:
def checkEmailValidity (email):
    if at and dotCom in email:
        return("It is an email")
    else:
        return("It is not an email")
email = "charisoneyemi@gmail.com"
at = "@"
dotCom =".com"

answer = checkEmailValidity (email)
print(answer)

It is an email


In [236]:
def checkEmailValidity (email, at, dotCom):
    if at in email and dotCom in email:
        return("It is an email")
    else:
        return("It is not an email")

print(checkEmailValidity("charisoneyemi@gmail.com", "@", ".com"))

It is an email


In [237]:
def checkEmailValidity (email, at, dotCom):
    if at in email and dotCom in email:
        return("It is an email")
    else:
        return("It is not an email")

print(checkEmailValidity("charisoneyemiatgmail.com", "@", ".com"))

It is not an email


In [23]:
def palindrome_checker(the_word):  # palindrome_checker is the identifier or function name and the_word is the parameter
    reverse_the_word = the_word[::-1]  # how to reverse the word
    
    if reverse_the_word == the_word:  # check if the reversed word is the same as the original
        return "It is a Palindrome"  # return this if it's a palindrome
    else:
        return "It is not a Palindrome"  # return this if it's not a palindrome

the_word = "madam"  # input word

answer = palindrome_checker(the_word)  # store the result in the variable 'answer'

print(f"The word '{the_word}' is {answer}")  # print the result with formatting


The word 'madam' is It is a Palindrome


In [20]:
def palindrome_checker(the_word):
    reverse_the_word = the_word[::-1]
    
    if reverse_the_word == the_word:
        return "It is a Palindrome"
    else:
        return "It is not a Palindrome"

answer = palindrome_checker("madam")
print(answer)

It is a Palindrome


###### find out what [-1::-1] does

### MOSH MOSH LOL FUNCTION

In [2]:
def greet():
    print("Hi there\n")
    print("Welcome aboard")
    
    
# To call the function
greet()

Hi there

Welcome aboard


#### Whats the diff btw greet and print?
#### print takes an input
#### greet doesn't take an input

In [3]:
def greet (fname, lname): #our parameters
    print(f"Hi {fname} {lname}")
    print("Welcome aboard")

#when calling we have to supply arguments for the greet function for the parameters
#a parameter is the input that you define for your function and the argument is the  actual value for a parameter
greet ("Alice", "Bay")

Hi Alice Bay
Welcome aboard


We have 2 types of functions
functions that 
- perform a task and 
- function that calculates and returns a values

In [5]:
def greeting(name):
    return (f"Hi {name}")
    #we use the return statement to return a value from this function
    
message = greeting("Mosh")
print(message)

Hi Mosh


In [6]:
def greet (fname, lname): #our parameters
    print(f"Hi {fname} {lname}")
    print("Welcome aboard")


print(greet ("Alice", "Bay"))

Hi Alice Bay
Welcome aboard
None


none is the return value of the function.
if we return something non won't show

In [1]:
def add1 (x, y):
    return x + y

result = add1(2,5)
print(result)
#or you can just do this
print(add1(2,5))
print(add1(2,4)) #this worked lol

add1(2,5)

7
7
6


7

In [12]:
def add1 (x, y):
    return x + y


print(add1(2,5))


7


In [13]:
def area2 (length, breadth):
    return length * breadth
print(area2(2,7))

14


In [14]:
#we can specify a default value to use incase it's not specified when calling it

def area3 (l,b=4):
    return l*b

print(area3(5))

20


In [15]:
def area3 (l,b=4):
    return l*b


area3(5)

20

### A function to convert from KM to meter

In [21]:
def kmConvert (meter):
    return meter / 1000

print(kmConvert(7))

0.007


### A function to convert from meter to KM

In [23]:
def meterConvert(km):
    return km * 1000

print(meterConvert(7))


7000


In [6]:
list1 = ['james', 'biodun', 'kaka', 'jumoke', 'bolaji']
list2 = [20, 56, 76, 30, 23, 40]


for name, age in zip(list1, list2):
    print(f"{name} {age}")

james 20
biodun 56
kaka 76
jumoke 30
bolaji 23


#### zip merges two list together as long as they have the same number or elements

In [7]:
list1 = ['james', 'biodun', 'kaka', 'jumoke', 'bolaji']
list2 = [20, 56, 76, 30, 23, 40]


for name, age in zip(list1, list2):
    print(name + " " + str(age)) #don't forget the str

james 20
biodun 56
kaka 76
jumoke 30
bolaji 23


#### now we want to push it to a txt file

## File handling

In [12]:
list1 = ['james', 'biodun', 'kaka', 'jumoke', 'bolaji']
list2 = [20, 56, 76, 30, 23, 40]

file_handle = open("output.txt", "w") #this is to write to a file named output.txt
for name, age in zip(list1, list2):#take note of the fact that the var names are d/f as in name age list1 list2
    file_handle.write(name + " " + str(age) + "\n")
file_handle.close()

#### the open function takes in two parameters where we want to write to and the mode of writing here is w. It could be read

##### file_handle.close() you can't rename till you close? ask chag if it's so

In [16]:
list1 = ['james', 'biodun', 'kaka', 'jumoke', 'bolaji']
list2 = [20, 56, 76, 30, 23, 40]
length = len(list)-1
tracker = 0

file_handle = open("output.txt", "w") #this is to write to a file named output.txt
for name, age in zip(list1, list2):#take note of the fact that the var names are d/f as in name age list1 list2
    if tracker < length:
tracker = tracker + 1
    else:
        file_handle.write(name + " " + str(age) + "\n")

file_handle.close()

IndentationError: expected an indented block after 'if' statement on line 8 (1391818986.py, line 9)

#### ask chag what the issue is here

In [37]:
# read from output.txt

#reader = open("output.txt", "r")
reader = open("/Users/caleboneyemi/Documents/charis.txt", "r")
for each_line in reader:
    print(each_line)
reader.close()

Hi my name is Charis, what is yours?


/Users/caleboneyemi/Documents/charis.txt

In [38]:
# read from output.txt

#reader = open("output.txt", "r")
reader = open("/Users/caleboneyemi/Documents/james.txt", "r")
for each_line in reader:
    print(each_line)
reader.close()

james 20

biodun 56

kaka 76

jumoke 30

bolaji 23


In [39]:
#HOME WORK create a function to check if a users passwork is correct

# NUMPY

Numpy is a multidimentional array library, ID, 2D, 3D, 4D...


Why we use Numpy over List

Numpy is faster than list because numpt uses fixed types

a = [1,3,5]
b = [1,2,3]
a*b = ERROR

a = np.array([1,3,5])
b = np.array([1,2,3])
a*b = np.array([1,6,15]

Applications of NunPy
- Matlab replacement
- Plotting
- Backend(Pandas, Connect 4, Digital Photography)
- Machine Learning


In [1]:
import numpy as np

The Basics

Initialize

In [4]:
a = np.array[1,2,3]
print(a)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b = np.array([1,3,5], [1,13,8])
print(b)

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [10]:
b = np.array([[1,3,5],[1,13,8]])
print(b)
#2d array

[[ 1  3  5]
 [ 1 13  8]]


How to get the dimension

In [11]:
a.ndim
#number dimesions

1

In [15]:
print(b.ndim)

2


In [12]:
a.shape

(3,)

In [14]:
b.shape
#ie 2x 3

(2, 3)

In [17]:
print(a.dtype)
#datatype

int64


In [18]:
print(b.dtype)


int64


In [22]:
#If you want to specify the type
aa = np.array([1,2,3], dtype = "int16")

In [24]:
print(aa.dtype)

int16


In [28]:
b.itemsize
#it's just telling you the number of bytes

8

In [26]:
a.itemsize

8

In [27]:
aa.itemsize

2

In [29]:
a.size

3

In [30]:
b.size
#that is the number of elements

6

In [31]:
#get total size
a.size * a.itemsize

24

In [34]:
#or you can just do
a.nbytes

24

Accessing or changing specific elements, rows, columns...

In [37]:
q = np.array([1,2,3,4,4,5,6,5,7,7,77], [2,4,5,12,4,5,7,4,6,78,56])
print(q)

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [38]:
q = np.array([[1,2,3,4,4,5,6,5,7,7,77], [2,4,5,12,4,5,7,4,6,78,56]])
print(q)

[[ 1  2  3  4  4  5  6  5  7  7 77]
 [ 2  4  5 12  4  5  7  4  6 78 56]]


In [39]:
q.shape

(2, 11)

In [43]:
# Get a specific element [r, c]
#remember indexing starts at 0 so the first row is 0 and the first column is 0

q[1, 6]

7

In [46]:
q[1,-5]

7

In [47]:
q[-1,-5]

7

In [49]:
# Get a specific row
q[0 :]

array([[ 1,  2,  3,  4,  4,  5,  6,  5,  7,  7, 77],
       [ 2,  4,  5, 12,  4,  5,  7,  4,  6, 78, 56]])

In [50]:
q[0, :]

array([ 1,  2,  3,  4,  4,  5,  6,  5,  7,  7, 77])

In [51]:
# So we have to put , else it will give us the whole array

In [52]:
#Get a specific column

q [: 6]

array([[ 1,  2,  3,  4,  4,  5,  6,  5,  7,  7, 77],
       [ 2,  4,  5, 12,  4,  5,  7,  4,  6, 78, 56]])

In [53]:
#same comma thing for column

In [54]:
q[:, 6]

array([6, 7])

In [55]:
# So this just gets the 7th column that is at index 6

In [56]:
#[start:end:step]

In [57]:
q[0, 1:8:2]
#that is in the first row, we want to get from the 2nd column at the 1st index to the 8th with the 8th not inclusive and we want it to skip

array([2, 4, 5, 5])

In [59]:
q[1, 1:-1:2]

array([ 4, 12,  5,  4, 78])

In [62]:
# Say we want to change something

q[0, 10]= 17
print(q)

[[ 1  2  3  4  4  5  6  5  7  7 17]
 [ 2  4  5 12  4  5  7  4  6 78 56]]


In [63]:
#lets not fotget indexing, i wanted to change the 10th element 
#from 7 to 7th but because I used the 10th index, it was the last
#so i'd change both now

q[0,9]= 17
q[0,10]= 77
print(q)

[[ 1  2  3  4  4  5  6  5  7 17 77]
 [ 2  4  5 12  4  5  7  4  6 78 56]]


In [65]:
#say i want to change all the values in a particular columns
q[:, 4]= 10
print(q)

[[ 1  2  3  4 10  5  6  5  7 17 77]
 [ 2  4  5 12 10  5  7  4  6 78 56]]


In [66]:
q[:, 7]= 15,14
print(q)

[[ 1  2  3  4 10  5  6 15  7 17 77]
 [ 2  4  5 12 10  5  7 14  6 78 56]]


3D Example

In [68]:
b = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# W3 Numpy

### Create a NumPy array:
np.array() is the function

In [70]:
my_arr= np.array([1,2,3,4,5])
print(my_arr)
print(type(my_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


NumPy is a Python library used for working with arrays.
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



## Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.




### 0-D array

In [72]:
#Create a 0-D array with value 42

scalar_arr = np.array(42)
print(scalar_arr)

42


### 1-D array
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.



In [73]:
oneD_arr = np.array([1,2,3,4,5])
print(oneD_arr)

[1 2 3 4 5]


### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors

In [74]:
twoD_arr = np.array([1,2,3], [4,5,6])
print(twoD_arr)

TypeError: Field elements must be 2- or 3-tuples, got '4'

### NOTE:
So when creating a 2D array you wrap each array in their own [] [] and the you wrap all in one [] with comma seperating the arrays inside ie [[],[]]

In [75]:
twoD_arr = np.array([[1,2,3], [4,5,6]])
print(twoD_arr)

[[1 2 3]
 [4 5 6]]


In [76]:
ndim(twoD_arr)

NameError: name 'ndim' is not defined

In [77]:
twoD_arr.ndim

2

In [80]:
twD_arr = np.array([[4,5,6]])
print(twD_arr)
twD_arr.ndim

[[4 5 6]]


2

In [81]:
tw_arr = np.array([[[4,5,6]]])
print(twD_arr)
tw_arr.ndim

[[4 5 6]]


3

### This is how you know the dimension. If it's in just one [ ] it's one dimension if it's two [[ ]] it's two dimension, if it's 3 [[[ ]]] its 3 dimension, even if it's just one element inside. For example look below:

In [82]:
testing1Dimension = np.array([1])
print(testing1Dimension)
print(testing1Dimension.ndim)

[1]
1


In [83]:
testing1Dimension = np.array([[1]])
print(testing1Dimension)
print(testing1Dimension.ndim)

[[1]]
2


In [84]:
testing1Dimension = np.array([[[1]]])
print(testing1Dimension)
print(testing1Dimension.ndim)

[[[1]]]
3


In [ ]:
threeD_arr = np.array()

In [85]:
s_arr = np.array([1,2,3,4,5])
print(s_arr)

[1 2 3 4 5]


In [87]:
print(s_arr.shape)
#That is how many elements are there

(5,)


### (5, ) meaning there are 5 elements in one dimension array. Returning (5,) indicates that s_arr is a 1D array (or a vector) with 5 elements, not a 2D array with rows and columns like in the (3, 4) case which means 3 rows and 4 columns

In [90]:
print(s_arr.ndim)
#ndim is the dimension in this case it's a 1 dimension array

1


In [126]:
ss_arr = np.array([2])
print(ss_arr)


[2]


In [127]:
print(ss_arr.shape)
print(ss_arr.ndim)

(1,)
1


In [93]:
d_arr = np.array([[1,3], [2,3], [5,4]])
print(d_arr)


[[1 3]
 [2 3]
 [5 4]]


In [94]:
print(d_arr.shape)
print(d_arr.ndim)

(3, 2)
2


In [95]:
#The shape is (3,2) meaning it's 3 rows and 2 columns

In [97]:
f_arr = np.array([[1,2,3,4], [5,4,3,2], [1,3,4,5]])
print(f_arr)

[[1 2 3 4]
 [5 4 3 2]
 [1 3 4 5]]


In [98]:
print(f_arr.shape)

(3, 4)


In [105]:
print(f_arr.ndim)

2


# The shoe rack example with Charis

In [109]:
shoeRack1 = np.array([1,2,3,4])
print(shoeRack1)

[1 2 3 4]


In [112]:
print(shoeRack1.shape)
#Getting the number of elements in a 1D
#Just for 1D

(4,)


In [111]:
print(shoeRack1.ndim)

1


In [117]:
shoeRack2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(shoeRack2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [118]:
print(shoeRack2.shape)

(3, 4)


In [119]:
shoeRack3 = np.array(
[
    [1,2],
    [3,4],
    [5,6],
    [7,8]
]
)

In [120]:
print(shoeRack3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [122]:
print(shoeRack3.shape)

(4, 2)


In [123]:
print(shoeRack3.ndim)

2


In [128]:
shoeRack4 = np.array(
[
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
]
)

In [129]:
print(shoeRack4)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [130]:
print(shoeRack4.shape)

(2, 3, 3)


In [131]:
shoeRack5 = np.array(
[
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ]
]
)

In [132]:
print(shoeRack5)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [133]:
print(shoeRack5.shape)

(3, 3, 3)


In [134]:
print(shoeRack5.ndim)

3


In [135]:
l = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])

In [136]:
print(l)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Getting a particular element

In [138]:
print(l[1,5])

13


### Slicing in numpy

In [139]:
print(l[0,:])

[1 2 3 4 5 6 7]


# Free code camp Numpy

In [140]:
a_arr = np.array([1,2,3])
print(a_arr)

[1 2 3]


In [141]:
b_arr = np.array([[1,2,3],[4,5,6]])
print(b_arr)

[[1 2 3]
 [4 5 6]]


### To get the dimensions, ndim

In [142]:
a_arr.ndim
a_arr.shape

(3,)

In [143]:
print(a_arr.ndim)

1


In [144]:
print(a_arr.shape)
#It's of size 3

(3,)


In [145]:
print(b_arr.ndim)
print(b_arr.shape)

2
(2, 3)


### Access specific elements, rows, columns

In [146]:
c_arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c_arr)
print(c_arr.ndim)#2 dimension
print(c_arr.size)#should be 2 x 7 ie 2 rows and 7 columns

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
2
14


### Get a specific element [r,c]
### Don't forget indexing

In [148]:
print(c_arr[1,5]) #ie the 2nd row and the 6th element in the 2nd row but 1,5 instead of 2,6 because of indexing

13


### Get a specific row

In [149]:
print(c_arr[0, :])
#We want the 1st row ie index 0 but since we want the whole row, we do the regular slicing technique : and leave it blank to show that it's everything

[1 2 3 4 5 6 7]


In [152]:
print(c_arr[0, 0:7])
#So this also works because we specified it, but you don't have to liek the above
#So 7 because in indexing, the number we put won't be included, if we left it at 6, the last element will not show

[1 2 3 4 5 6 7]


### Get a specific column

In [154]:
print(c_arr[:, 2])
#the comma is after the number on the lhs and before on the rhs
#so this returns column 3 but index 2 column

[ 3 10]


### Getting a little more fancy [start:end:step]

In [155]:
print(c_arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [157]:
#So let's say we want to get 2,4,6 from the first row
print(c_arr[0, 1:6:2])
#that is 0 for the first row
#then in the first row, start at index 1 down to index 6 excluding index 6 and step by 2

[2 4 6]


In [158]:
#Let's say we want to get 11 and 13 from the second row
print(c_arr[1, 3:6:2])

[11 13]


In [159]:
#let's say we want to get the first and last column
print(c_arr[:, 0,7])

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [161]:
# remember to get a particular column we do
print(c_arr[:, 4])#this returns the 5the column

[ 5 12]


In [162]:
#Now if we want to get two columns at once from a 2D array, we do this
#say we want to get the 1st and last columns
print(c_arr[:, [0,7]])



IndexError: index 7 is out of bounds for axis 1 with size 7

In [163]:
print(c_arr[:, [0,6]])


[[ 1  7]
 [ 8 14]]


So for slicing, you know how, it's one before the actual nuber, like column 5 will be index 4 

And then when we want to print the whole array out, we include the actual length like
atest= [1,8,9]
print(atest[0:3]) 

if we leave it at 2, it won't print it all out.

But in the case of print a particular column in numpy whether it is the last column or not, it's just the index we are looking at, we're not checking if it's the last and doing that length stuff

In [165]:
atest= [1,8,9]
print(atest[0:2])

[1, 8]


In [166]:
atest= [1,8,9]
print(atest[0:3])

[1, 8, 9]


In [167]:
print(c_arr[0, 1:-1:2])

[2 4 6]


In [169]:
print(c_arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [182]:
#Say we want to change 5 to 55, here's what we do

#print(c_arr[0:, 5])# this is to get the 5 column actally although that 0 is not needed
# to get a specific element, we do [r,c]
print(c_arr[0,4])

#now chnaging it would be
#print(c_arr[0,5]=20) don't print this way, run first then print

c_arr[0,4] = 55
print(c_arr)


55
[[ 1  2  3  4 55  6  7]
 [ 8  9 10 11 12 13 14]]


5 will now be 55

Say we want to change a whole column, let's do that will the last column

In [183]:
c_arr[:, 6] = 77
print(c_arr)

[[ 1  2  3  4 55  6 77]
 [ 8  9 10 11 12 13 77]]


# 3D NUMPY ARRAY

In [187]:
threeD_arr = [[[1,2,3],[4,5,6]], [[11,22,33], [44,55,66]]]


print(threeD_arr)



[[[1, 2, 3], [4, 5, 6]], [[11, 22, 33], [44, 55, 66]]]


In [188]:
threeD_arr.ndim


AttributeError: 'list' object has no attribute 'ndim'

The above gave an errror because, we didn't specify it as a numpy, it's a list here

In [190]:
threeD_arr = [[[1,2,3],[4,5,6]], [[11,22,33],[44,55,66]]]
print(threeD_arr.ndim)





AttributeError: 'list' object has no attribute 'ndim'

# Take note of this error, stop forgetting to put your np.array() function

In [192]:
threeD_arr = np.array([[[1,2,3],[4,5,6]], [[11,22,33],[44,55,66]]])

print(threeD_arr)



[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


Now to get a particular element in your 3 D array, remember the 2D was like below

In [196]:
twoD2 = np.array([[1,2,3],[1,3,5]])
print(twoD2)

#to get a specific element is 
print(twoD2[1,2])#This will get row 2 index 1 and row 3 index 2


[[1 2 3]
 [1 3 5]]
5


Now in 3D, we do this, we first condider the outer like we have 2 shelves or 3 shelves... We first say,w hich shelf are we looking at, the in that shelf, which row then whuch element

In [198]:
print(threeD_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [201]:
# Say we want 33
# 33 IN IN THE SECOND SHELF AT INDEX 1, IT'S IN THE FIRST ROW AT INDEX 0 AND IT'S THE 3RD INDEX
print(threeD_arr[1,0,2])




33


In [202]:
print(threeD_arr.ndim)

3


In [204]:
print(threeD_arr.shape)
# It will give (2,2,3)
# That is 2 shelves, and each of the shelves have 2 rows and 3 columns


(2, 2, 3)


### Say we want to get the last rows in our 3D, like all of them from all shelves

#### That is in the case of threeD_arr we want to get 4,5,6 and 44,55,66

In [205]:
print(threeD_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [206]:
print(threeD_arr[:,1:])

[[[ 4  5  6]]

 [[44 55 66]]]


So what this means is that 
: we want all 
,1 we want the 2 row that is at index 1
": " ie the column and space just wants to get all of it from that 2nd row which is at index 1


chag

: selects all sub-arrays (both sub-arrays).
1: means "start from row 1 and include all subsequent rows" for each sub-array.

Let's try this out by trying to get the first row

In [207]:
print(threeD_arr[:,0:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


The above prints all, that's not what we want, that happened because we didn't specify the last

In [208]:
print(threeD_arr[:,0:1])

[[[ 1  2  3]]

 [[11 22 33]]]


0:1 means "select row 0 but keep it as a sub-array," keeping the shape of the result as a 3D array.
: selects all elements (columns) in that row.


# Initialize different types of arrays

In [265]:
# All 0's matrix
zeros = np.zeros((2,3))# 2 dimension. So just 1 shelf that had 2 rows and 3 columns
print(zeros)
print(zeros.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2


In [216]:
# All 0's matrix
zeros = np.zeros((2,3,4))# 3 dimension
print(zeros)
print(zeros.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


In [218]:
#All 1s matrix
one = np.ones((4,2,3))
print(one)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [220]:
fullmatrix = np.full((2,2), 99)
# It takes two values, the shape and then the element we want in it

#By the shape, i mean a 2x2 matrix, ie 2 rows and 2 columns 
print(fullmatrix)


[[99 99]
 [99 99]]


In [221]:
test3x2_55 = np.full((3,2), 55)

print(test3x2_55)

[[55 55]
 [55 55]
 [55 55]]


In [224]:
test4_3x2_55 = np.full((4,3,2), 55)
print(test4_3x2_55)
#The shape has 4 shelves, 3 rows and 2 columns in each

[[[55 55]
  [55 55]
  [55 55]]

 [[55 55]
  [55 55]
  [55 55]]

 [[55 55]
  [55 55]
  [55 55]]

 [[55 55]
  [55 55]
  [55 55]]]


### Full like, allows us to use the sixe if a particular array

In [225]:
copying_c_arr = np.full((c_arr), 7)

TypeError: only integer scalar arrays can be converted to a scalar index

In [238]:
copying_c_arr = np.full(c_arr.shape, 7)

In [236]:
copying_c_arr(c_arr.shape, 7)

TypeError: 'numpy.ndarray' object is not callable

In [235]:
copying_c_arr.full(c_arr.shape, 7)

AttributeError: 'numpy.ndarray' object has no attribute 'full'

In [239]:
copying_c_arr = np.full(c_arr.shape, 7) # don't do this

In [233]:
np.full(c_arr.shape, 7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [232]:
np.full(test4_3x2_55.shape, 7)

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])

 ## Initialize a matrix of random decimal numbers

In [245]:
ran = np.random.rand(4,2)
print(ran)
# rand means Each value in the array is a random floating-point number in the range [0, 1).


[[0.72983568 0.55004443]
 [0.23923367 0.10330459]
 [0.12027251 0.02053589]
 [0.54607705 0.83396793]]


In [244]:
ran2 = np.random(4,2)
print(ran2)

TypeError: 'module' object is not callable

In [247]:
ran3 = np.random.rand(4,3,2)
print(ran3)

[[[0.47855061 0.30080666]
  [0.29570253 0.32453032]
  [0.30663414 0.68052096]]

 [[0.58546576 0.93058948]
  [0.51680113 0.82095531]
  [0.3606895  0.76000756]]

 [[0.74306859 0.14655501]
  [0.53879046 0.68736856]
  [0.23172874 0.11996277]]

 [[0.03836628 0.30797489]
  [0.27390451 0.14081185]
  [0.32560022 0.95379385]]]


 ## Initialize a matrix of random integer numbers

In [248]:
ranInt = np.random.randint(4,3,2)

ValueError: low >= high

So rand is different from randint and for randint, we don't just do (the 4,3,2 ie 4 shelves with 2 rows and 3 columns), we actually do the number we want (not exactly the number we want, like if we say 5, it picks between 0 and 5 and 0 is inclusive and 5 is exclusive), the size=(3 rows, 4 columns)


If you don't want 0-7, you can specify

4,7

In [256]:
ranInt4_7 = np.random.randint(4,7, size=(3,2))
print(ranInt4_7)

[[4 5]
 [6 5]
 [6 4]]


In [252]:
ranInt = np.random.randint(7, size=(4,2)) 
print(ranInt)

[[3 6]
 [3 3]
 [5 5]
 [6 5]]


I forgot to say this if we dont specify the size, it jsu

In [254]:
ranInt2 = np.random.randint(7) 
print(ranInt2)

0


In [257]:
ranInt4_7 = np.random.randint(-2,7, size=(3,2))
print(ranInt4_7)

[[ 0  3]
 [ 5 -1]
 [ 2  6]]


In [258]:
# Identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [260]:
fiveIden = np.identity(5)
print(fiveIden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## To repeat an array let;s say 2 times

In [262]:
arr2repeat = np.array([1,2,3,4])
rptarr2repeat = np.repeat(arr2repeat, 2)
print(rptarr2repeat)

[1 1 2 2 3 3 4 4]


In [274]:
#repeating 3 times

arr2repeat = np.array([1,2,3])
rptarr2repeat = np.repeat(arr2repeat, 3)
print(rptarr2repeat)

[1 1 1 2 2 2 3 3 3]


If you want to repeat it like
123
123
123
we make the array 2 Dimensional by wrapping it in another [] and then we specify our axis =0



In [276]:
#repeating 3 times

arr2repeat = np.array([[1,2,3]])
rptarr2repeat = np.repeat(arr2repeat, 3, axis = 0)
print(rptarr2repeat)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


If we leave the axis as one, it doesn't do it like the above but like the previous above

In [283]:
arr2repeatagain = np.array([[1,2,3]])
uu = np.repeat(arr2repeatagain, 3, axis= 1)
print(uu)

[[1 1 1 2 2 2 3 3 3]]


In [285]:
arr2repeatagain = np.array([[1,2,3]])
ww = np.repeat(arr2repeatagain, 3, axis= 0)
print(ww)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Element Wise Addition

In [264]:
u = np.array([2,3,4,5])
additionWith2 = u + 2
print(additionWith2)

[4 5 6 7]


# Linear ALgebra

In [269]:
m1 = np.ones((2,3))
print(m1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [272]:
m2 = np.full((2,3), 9)
print(m2)

[[9 9 9]
 [9 9 9]]


In [273]:
d = np.matmul(m1,m2)
print(d)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

So the above didn't work because of our matrix rule where if we have to multipy a matrix, the columns of the first have to be same as the rows of the second (like same number)

So let's redo it

In [290]:
matrix1 = np.ones((2,3))


matrix2 = np.full((3,7), 4)

uuu = np.matmul(matrix1, matrix2)

print(uuu)



[[12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12.]]


So this is how we got 12

Our matrix1 basically is a 2 x 3 matrix of only one's and our matrix2 is a 3 X 7 matrix with 2 as elements

So the first element in the uuu is calculated by

(matrix1 * matrix2) + (matrix1 * matrix2) +(matrix1 * matrix2)

It's 3 times because 3 columns are multiplying 3 rows

So it's (1*4) + (1*4) + (1*4)

Then the shape is obviously 2 by 7 because 2 rows and 7 columns 

Let's test the reverse for better understanding

In [291]:
mat1 = np.full((2,7), 4)
mat2 = np.ones((2,3))

mat1_2 = (mat1, mat2)
print(uv)

NameError: name 'uv' is not defined

In [295]:
mat1 = np.full((2,7), 4)
mat2 = np.ones((2,3))
mat1_2 = np.mathmul(mat1,mat2)
print(mat1_2)

AttributeError: module 'numpy' has no attribute 'mathmul'

In [296]:
mat1 = np.full((2,7), 4)
mat2 = np.ones((2,3))
mat1_2 = matmul(mat1,mat2)
print(mat1_2)

NameError: name 'matmul' is not defined

In [298]:
mat1 = np.full((3,7), 4)
mat2 = np.ones((2,3))
mat1_2 = np.matmul(mat1,mat2)
print(mat1_2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 7)

The issue was the column number and row number not being the same, so I flipped it

In [299]:
mat1 = np.full((7,3), 4)
mat2 = np.ones((3,2))
mat1_2 = np.matmul(mat1,mat2)
print(mat1_2)

[[12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]]


### So in essence, let's compare to see the difference

In [300]:
matrix1 = np.ones((2,3))


matrix2 = np.full((3,7), 4)

uuu = np.matmul(matrix1, matrix2)

print(uuu)



[[12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12.]]


In [301]:
mat1 = np.full((7,3), 4)
mat2 = np.ones((3,2))
mat1_2 = np.matmul(mat1,mat2)
print(mat1_2)

[[12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]]


So  I had earlier said this for the first that is uuu

Then the shape is obviously 2 by 7 because 2 rows and 7 columns

Let's test the reverse for better understanding


So yes, to knwo the shape, it take the number of rows of the first and the number of columns of the second. Just like we compared col of 1st to row of 2nd now we're doing the normal way, row of first and column of 2nd to know th shape

In [304]:
print(uuu.ndim)
print(mat1_2.ndim)

2
2


## Sum

In [314]:
sd = np.array([[1,2,3], [4,5,6]])
print(sd.shape)

print(sd)

print(sd.ndim) 


(2, 3)
[[1 2 3]
 [4 5 6]]
2


Here, axis=0 means you are summing vertically along the columns ie 1+4 =5, 2+5 = 7, 3+6 = 9

Here, axis=1 means you are summing horizontally along the row ie 1+2+3 = 6, 4+5+6 = 15


## Axis 0  does in this direction |
## Axis 1 does in this direction ___


In [315]:
print(np.sum(sd, axis = 0))
print(np.sum(sd, axis = 1))

[5 7 9]
[ 6 15]


## Getting data from txt file

In [317]:
# Define the content you want to write to the file
content = """1,2,3,4,5,6,7
12,34,67,8,0,12,34
3,4,6,7,89,12,12
"""

# Specify the file path where you want to save the file
file_path = 'scores.txt'  # This will save in the current working directory of the Jupyter notebook

# Open the file in write mode and write the content
with open(file_path, 'w') as file:
    file.write(content)

print("File 'scores.txt' created successfully.")


File 'scores.txt' created successfully.


Explanation:
np.genfromtxt("scores.txt", delimiter=','):

np.genfromtxt(): This is a function from the NumPy library used to read data from a text file and convert it into a NumPy array. It's particularly useful for loading numerical data and handling missing values.

"scores.txt": This is the name of the text file you want to read. The file should be located in the same directory as your Python script or Jupyter Notebook, or you should provide the full path to the file if it's located elsewhere.

delimiter=',': This specifies the character that separates values in the file. In this case, the values are separated by commas, which is typical for CSV (Comma-Separated Values) files.

In [321]:
sh2 = np.genfromtxt("scores.txt", delimeter = ",")
print(sh2)

TypeError: genfromtxt() got an unexpected keyword argument 'delimeter'

In [322]:
sh2 = np.genfromtxt("scores.txt", delimiter = ",") 
#miter not meter
print(sh2)

[[ 1.  2.  3.  4.  5.  6.  7.]
 [12. 34. 67.  8.  0. 12. 34.]
 [ 3.  4.  6.  7. 89. 12. 12.]]


In [323]:
print(sh2.shape)

(3, 7)


In [326]:
greaterThan10 = (sh2 > 10)
print(greaterThan10)

[[False False False False False False False]
 [ True  True  True False False  True  True]
 [False False False False  True  True  True]]


Printing directly
print(greaterThan10)
Will give true and false values


But If you want to get teh actual values then sh2[greatThan10]


In [328]:
print(greaterThan10)
print(sh2[greaterThan10])

[[False False False False False False False]
 [ True  True  True False False  True  True]
 [False False False False  True  True  True]]
[12. 34. 67. 12. 34. 89. 12. 12.]


## Get Average from the txt

In [331]:
print(sh2)

[[ 1.  2.  3.  4.  5.  6.  7.]
 [12. 34. 67.  8.  0. 12. 34.]
 [ 3.  4.  6.  7. 89. 12. 12.]]


In [332]:
avgofScores = np.average(sh2)
print(avgofScores)

15.619047619047619


## Get Min and Max from the txt


In [334]:
max = np.max(sh2)
print(max)

min = np.min(sh2)
print(min)

89.0
0.0


# Get >= 

In [338]:
thirtyAndAbove = sh2 >= 30 #True and False values
print(thirtyAndAbove)


number = sh2[thirtyAndAbove]# Essentially, this translates to extracting the actual numbers from sh2 that meet the condition (being 30 or greater).
print(number)
print(len(number))




[[False False False False False False False]
 [False  True  True False False False  True]
 [False False False False  True False False]]
[34. 67. 34. 89.]
4


In [342]:
# These are salaries for 3 months

jeff_salary = [2700,3000,3000]
nick_salary = [2600,2800,2800]
tom_salary = [2300,2500,2500] 

base_salary = np.array([jeff_salary, nick_salary, tom_salary])
print(base_salary)

# we're just merging here

[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]]


In [343]:
jeff_bonus = [500,400,400]
nick_bonus = [600,300,400]
tom_bonus = [200,500,400]
bonus = np.array([jeff_bonus, nick_bonus, 
tom_bonus])
print(bonus)

# we're just merging here

[[500 400 400]
 [600 300 400]
 [200 500 400]]


In [346]:
salary_bonus = base_salary + bonus
print(salary_bonus)


print(type(salary_bonus))


[[3200 3400 3400]
 [3200 3100 3200]
 [2500 3000 2900]]
<class 'numpy.ndarray'>


So we just added them

In [348]:
#Say we want to find the max value of the base salary

print(salary_bonus.max())

3400


We want to determine the max amount paid to each employee in the past 3 month

In [349]:
print(np.amax(salary_bonus, axis = 1))
remember axis is left to right ---

[3400 3200 3000]


In [2]:
# Just testing something in list

testlist = [1,2,3,4,5,6,7]
print(testlist[:-1])


#So it prints all except the last index



[1, 2, 3, 4, 5, 6]


In [22]:
church7 = 7
church_ = 8
print (church_)









8


# Exam prep


In [63]:
# ag = "Hello, World!"

# print(ag[-1:6:2])



# K = 500
# print(k)






t ="james kaka"
print(t[2:])
print(t[2:5])
print(t[0:5])
print(t[-5:])
t2 ="james kaka"
print(t2[1:1])#empty

mes kaka
mes
james
 kaka



In [48]:
list17 = ['physics', 'chemistry', 1997, 2000]
list27 = [1, 2, 3, 4, 5, 6, 7 ]

print (list27[1:5])




[2, 3, 4, 5]


In [50]:

list17[2] = 2001
print(list17)




['physics', 'chemistry', 2001, 2000]


In [51]:
print(list17[2])



2001


In [52]:
del list17[2]
print(list17)

['physics', 'chemistry', 2000]


In [53]:
print(list17[2])


2000


In [54]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [55]:
['Hi!'] * 4

['Hi!', 'Hi!', 'Hi!', 'Hi!']

In [57]:
L = ['C++', 'Java', 'Python']
print(L[2])
print(L[-2] )
print(L[1:])

Python
Java
['Java', 'Python']


In [58]:
card= [1,2,3]
card2 = [4,7]

card.extend(card2)
print(card)

[1, 2, 3, 4, 7]


In [59]:
card3 = [1,3,7,9,0,5]
card3.insert(2, 10)
print(card3)



[1, 3, 10, 7, 9, 0, 5]


In [61]:
card4 = [1,3,7,9,0,5]
card5 = [10,5]
card4.insert(2, card5)
print(card4)



[1, 3, [10, 5], 7, 9, 0, 5]


In [66]:
aaaas = [1, 2, 3, 4, 5] 
lengthaaaas = len(aaaas)
print(lengthaaaas)

5


In [67]:
aaaahs = [11,2,4,9,3]
aaaahs.sort()
print(aaaahs)

[2, 3, 4, 9, 11]


In [70]:
aaaahs.reverse()
print(aaaahs)

[11, 9, 4, 3, 2]


In [78]:
numbersj = [3, 1, 4, 1, 5, 9]
numbersj.sort(reverse=True)
print(numbersj) 

[9, 5, 4, 3, 1, 1]


In [80]:
numbersjj = [3, 1, 4, 1, 5, 9]
index = numbersjj.index(1)
print(index)

1


In [82]:
count = numbersjj.count(1)
print(count)

2


In [83]:
ht =  ['maths', 'biology']
ht = ht * 2
print(ht)

['maths', 'biology', 'maths', 'biology']


In [85]:
hf =  ['physics', 'chemistry', 1997, 2000]
del hf[2]
print(hf[2])



2000


In [91]:
hf2 = [1,3,4,5]*2
print(hf2)
print(hf2+hf)


[1, 3, 4, 5, 1, 3, 4, 5]
[1, 3, 4, 5, 1, 3, 4, 5, 'physics', 'chemistry', 2000]


In [88]:
print(hf2[4])

1


In [92]:
hf3 = [1,3,4,5]
print(hf3[-3:])
print(hf3[1:])
print(hf3+hf3)

[3, 4, 5]
[3, 4, 5]
[1, 3, 4, 5, 1, 3, 4, 5]


In [95]:
hf4= [4,5,6,2,5,6,7,1,3,8]
print(hf4[1:6:2])

[5, 2, 6]


In [97]:
print(hf4[-1:])

[8]


In [98]:
print(hf4[-1::-3])

[8, 7, 2, 4]


In [104]:
hf5 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
print(hf5[0::3])

[1, 4, 7, 10]


In [106]:
print(hf5[-1::-3])

[12, 9, 6, 3]


In [107]:
print(hf5[-1::3])

[12]


In [109]:
print(hf5[1::-3])

[2]


In [110]:
print(hf5[-1:])

[12]


In [111]:
print(hf5[-1::3])

[12]


In [112]:
print(hf5[1::3])

[2, 5, 8, 11]


In [113]:
print(hf5[-1::-3])

[12, 9, 6, 3]


In [114]:
hf6 = [4, 5, 6, 7, 8, 4, 0]
print(hf6[::-1])

[0, 4, 8, 7, 6, 5, 4]


In [116]:
xd= False
print(type(xd))

<class 'bool'>


In [140]:
my_stringXD = 'Hello World!'
print(my_stringXD[1])
print (my_stringXD[2:5])
print (my_stringXD[2:])


e
llo
llo World!


In [129]:
my_stringXfD = 'Hi ya'
print(len(my_stringXfD))

5


In [134]:
my_stringXD = 'Hello World!'
slicedmy_stringXD = my_stringXD[2:6]
print(slicedmy_stringXD)


llo 


In [135]:
print(len(slicedmy_stringXD))

4


In [141]:
age = 23
print(ag%e)

NameError: name 'e' is not defined

In [145]:
_try = 23
print(_try)
#try is a keyword but not _try

23


In [168]:
my_stringtry = "Hello, World!"
substringtry = my_stringtry[-1:6:2]
print(substringtry)

In [154]:
print(len(substringtry))

3


In [11]:
vc= [1,2,3,10]
print(vc.index(10))
cv= 10
vcc = [2,3,4]

vc.insert(2, vcc)
print (vc)


3
[1, 2, [2, 3, 4], 3, 10]


In [10]:
vc.index(10) #now 4 and not 3

4

In [12]:
vc = [1,3,4,5]*2
print(vc[-3:])

[3, 4, 5]


In [13]:
print(vc)

[1, 3, 4, 5, 1, 3, 4, 5]


In [14]:
vc[-1:]

[5]

In [15]:
vc[-1::3]

[5]

In [18]:
vc.rfind(4)

AttributeError: 'list' object has no attribute 'rfind'

In [20]:
str1 = "Welcome to tutorialspoint"

index = str1.rindex('t')
print(index)

24


In [25]:

str1 = "Welcome to tutorialspoint"

index = len(str1) - 1 - str1[::-1].index('t')
print(index)

24


In [28]:
ggggg= "Hello, World!"
print(ggggg[-1:6:-1])
print(ggggg[-1:-6:-1])

!dlroW
!dlro


# NOTE!!!!

In [54]:
hhhhh= "Trichology!"
print(hhhhh[-1:6:-1])
print(hhhhh[-1:-6:-1])
print(hhhhh[-1:-6]) #EMPTY
print(hhhhh[-1:6]) #EMPTY
print(hhhhh[-1:]) #!
print(hhhhh[-1::]) #!
print(hhhhh[-1::1]) #!
print(hhhhh[-1:-1]) #EMPTY
print(hhhhh[-1::-1]) #REVERESE
print(hhhhh[-1:-1:-1]) #REVERESE
print(hhhhh[-1:1:-1]) #REVERSE W/O STOPPING AT 1 EXCLUDING 1
print(hhhhh[-1:1:1]) #REVERSE W/O STOPPING AT 1 EXCLUDING 1


!ygo
!ygol


!
!
!

!ygolohcirT

!ygolohci



In [47]:
print(hhhhh[-1:1:1]) #REVERSE W/O STOPPING AT 1 EXCLUDING 1

In [57]:
print(hhhhh[1:90])
print(hhhhh[10:90])
print(hhhhh[90])

richology!
!


IndexError: string index out of range

In [50]:
e = [1, 'hi', "hey"]

In [51]:
print(e)

[1, 'hi', 'hey']


In [52]:
f = [1,2,3,4]
print(f[2:9])

[3, 4]


In [60]:
x = (1,2,3,4)
x[3]= 9
print(x)

TypeError: 'tuple' object does not support item assignment

In [66]:
x = (1,2,3,4)
y = (9)
d = y+x
print(d)

TypeError: can only concatenate str (not "tuple") to str

In [67]:
tup1 = (12, 34.56)
tup2 = ('abc', 'xyz')
tup3 = tup1 + tup2
print (tup3)

(12, 34.56, 'abc', 'xyz')


In [70]:
x = (1,2,3,4)
y = ('dd')
z = x + y
print(z)

TypeError: can only concatenate tuple (not "str") to tuple

In [71]:
x = (1,2,3,4)
y = ('dd', 'll')
z = x + y
print(z)

(1, 2, 3, 4, 'dd', 'll')


In [72]:
x = (1,2,3,4)
y = (9,5)
d = y+x
print(d)

(9, 5, 1, 2, 3, 4)


In [74]:
x = [1,2,3,4]
y = [9]
d = x+y
print(d)

[1, 2, 3, 4, 9]


In [75]:
x = (1,2,3,4)
y = ('dd',)
z = x + y
print(z)

(1, 2, 3, 4, 'dd')


In [77]:
x = (1,2,3,4)
y = (9,)
d = x+y
print(d)

(1, 2, 3, 4, 9)


In [81]:
x = (1,2,3,4)

listx = list(x)
listx.del(3)
print(listx)

SyntaxError: invalid syntax (3495437385.py, line 4)

In [82]:
x = (1,2,3,4)

listx = list(x)
listx.remove(3)
print(listx)

[1, 2, 4]


In [88]:
x = (1,2,3,11)

listx = list(x)
listx.remove(11)
x = listx

print(x)

[1, 2, 3]


In [90]:
print (type(x))

<class 'list'>


In [91]:
x = tuple(listx)
print(x)

(1, 2, 3)


In [93]:
s = (1, 2, 3) + (4, 5, 6) 
j = ('Hi!',) * 4

print(s)
print(j)


(1, 2, 3, 4, 5, 6)
('Hi!', 'Hi!', 'Hi!', 'Hi!')


In [96]:
s = [1, 2, 3] + [4, 5, 6]
j = ['Hi!',] * 4

print(s)
print(j)


[1, 2, 3, 4, 5, 6]
['Hi!', 'Hi!', 'Hi!', 'Hi!']


In [101]:
T=('C++', 'Java', 'Python')
print(T[2]) 
print(T[-2]) 
print(T[1:])
print(T[-3:])

Python
Java
('Java', 'Python')
('C++', 'Java', 'Python')


In [106]:
dict = {"name":"esther", "age":24, "class":"first"}
print(dict)

{'name': 'esther', 'age': 24, 'class': 'first'}


In [107]:
print(dict[age])

NameError: name 'age' is not defined

In [108]:
print(dict["age"])

24


In [109]:
#Updating it
dict["school"]= "FA"
print(dict)

{'name': 'esther', 'age': 24, 'class': 'first', 'school': 'FA'}


In [111]:
dict["age"]=14
print(dict)

{'name': 'esther', 'age': 14, 'class': 'first', 'school': 'FA'}


In [114]:
list2 = ['maths', 'biology']
list2 = list2 * 2
print(list2)

['maths', 'biology', 'maths', 'biology']


In [116]:
tup1 = (12, 34.56,45)
#tup1[0] = 13
print(tup1[-1])

45


## TESTING CLASS WORK LECTURE 6

In [117]:
a = ['physics', 'chemistry', 1997, 2000]
a[9] = 8
print(a)

IndexError: list assignment index out of range

In [118]:
a = ['physics', 'chemistry', 1997, 2000]
del a[4]
print(a)

IndexError: list assignment index out of range

In [119]:
list2 = ['maths', 'biology']
list2 = list2 *2
print (list2)

['maths', 'biology', 'maths', 'biology']


In [120]:
list = ['physics', 'chemistry', 1997, 2000]
print(list[-3:])

['chemistry', 1997, 2000]


In [121]:
tup1 = (12, 34.56,45)
tup1[0] = 13
print(tup1[-1])

TypeError: 'tuple' object does not support item assignment

In [124]:
k = {"name":"kaz","age":12}
print(k['name'])


kaz


In [125]:
k['sex'] = 'M'
print(k['seX'])

KeyError: 'seX'

In [126]:
list1 = ['physics', 'chemistry', 1997, 2000]
list2 = [1, 2, 3, 4, 5, 6, 7 ]
print(list1[2])

1997


In [127]:
a = ['physics', 'chemistry', 1997, 2000]
del a[2]
print(a[2])

2000


In [128]:
a = ['physics', 'chemistry', 1997, 2000]
a[4] = 3000
print(a[4])

IndexError: list assignment index out of range

In [130]:
list1 = ['physics', 'chemistry', 1997, 2000]
list2 = [1, 2, 3, 4, 5, 6, 7 ]
print('element in the zeroth index is: ', list1[2])

element in the zeroth index is:  1997


In [131]:
a = ['physics', 'chemistry', 1997, 2000]
del a[2]

In [132]:
print(a[2])

2000


In [133]:
a[4] = 3000
print(a[4])

IndexError: list assignment index out of range

In [134]:
s = [1,3,4,5]*2
print(s[8])

IndexError: list index out of range

In [135]:
s = [1,3,4,5]
print(s[-3:])
print(s[1:])

[3, 4, 5]
[3, 4, 5]


In [137]:
b= 6 
a = (4,3,4,5,6) 
b = a[3]
a[4]=7
print(a[4])

TypeError: 'tuple' object does not support item assignment

In [139]:
list = ['physics', 'chemistry', 1997, 2000]
list2 = ['maths', 'biology']
list2 = list2 *2
del list2[3]
list = list + list2
print (list)

['physics', 'chemistry', 1997, 2000, 'maths', 'biology', 'maths']


In [140]:
list = ['physics', 'chemistry', 1997, 2000]
print(list[-3:])

['chemistry', 1997, 2000]


In [141]:
tup1 = (12, 34.56)
tup1[0] = 13
print(tup1[0])

TypeError: 'tuple' object does not support item assignment

In [143]:
list3 = (10, 4, 5)
list3[1] = 15
print(list3)
#actually a tuple nt list

TypeError: 'tuple' object does not support item assignment

In [148]:
a = 5
b = 10
if(a == b):
    print('a and b are the same')
elif(a > b):
    print(f"{a} is greater than {b}")
elif(a >= b):
    print(f"{a} is greater than or equal to {b}")
elif(a =! b):
    print(f"{a} is not equal to {b}")
elif(a <= b):
    print(f"{a} is less than or equal to {b}")
elif(a < b):
    print(f"{a} is less than {b}")
    


SyntaxError: invalid syntax (952659000.py, line 9)

In [149]:
a = 5
b = 10
if(a == b):
    print('a and b are the same')
elif(a > b):
    print(f"{a} is greater than {b}")
elif(a >= b):
    print(f"{a} is greater than or equal to {b}")
elif(a != b):
    print(f"{a} is not equal to {b}")
elif(a <= b):
    print(f"{a} is less than or equal to {b}")
elif(a < b):
    print(f"{a} is less than {b}")
    


5 is not equal to 10


In [150]:
a = 5
b = 10
if(a == b):
    print('a and b are the same')
elif(a > b):
    print(f"{a} is greater than {b}")
else:
    print(f"{a} is less than {b}")
    


5 is less than 10


In [145]:
a = True
b = False
if (a == b):
    print('a and b are the same')
else:
    print('a and b are not the same')

a and b are not the same


In [146]:
a = False
b = False
if (a == b):
    print('a and b are the same')
else:
    print('a and b are not the same')

a and b are the same


In [147]:
a = True
b = True
if (a == b):
    print('a and b are the same')
else:
    print('a and b are not the same')

a and b are the same


In [ ]:
a = True
b = True
if (a == b):
    print('a and b are the same')
else:
    print('a and b are not the same')

In [152]:
a = True
b = True
if (a and b):
    print('a and b are the same')
else:
    print('a and b are not the same')

a and b are the same


In [154]:
a = 5
b = 10
if (a and b):
    print('a and b are the same')
else:
    print('a and b are not the same')

a and b are the same


In [155]:
#the if (a and b): statement does not compare a and b directly. Instead, it checks if both a and b are truthy values (non-zero, non-None, etc.).



In [156]:
a = True
b = False
if (a and b):
    print('a and b are the same')
else:
    print('a and b are not the same')

a and b are not the same


In [157]:
a = True
b = False
if (a and b):
    print('a and b are the same')
else:
    print('a and b are not the same')

a and b are not the same


In [158]:
a = True
b = False
if (a or b):
    print('a and b are the same')
else:
    print('a and b are not the same')

a and b are the same


In [159]:
a = True
b = False
if (a not b):
    print('a and b are the same')
else:
    print('a and b are not the same')

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2856899342.py, line 3)

In [160]:
x = 10
y = 20
if x > 5 and y < 30:
    print("Both conditions are True")  # This will print


Both conditions are True


In [161]:
a = True
b = False
if a or b:
    print("At least one is True")  # This will print because a is True
else:
    print("Both are False")


At least one is True


In [162]:
x = 10
if not x > 15:
    print("x is not greater than 15")  # This will print because x is not > 15


x is not greater than 15


In [163]:
x = 10
y = 20
if x > 5 or y > 30:
    print("At least one condition is True")  # This will print because x > 5 is true
else:
    print("Both conditions are False")


At least one condition is True


In [166]:
x = 10
y = 20
if not x > 15:
    print("x is not greater than 15")  # This will print because x > 15 is False, so not False is True
else:
    print("x is greater than 15")


x is not greater than 15


In [168]:
i='isms'
for letter in i:
    print (letter)

i
s
m
s


In [169]:
i='isms'
for letter in i:
    print (letter, end = " ")

i s m s 

In [172]:
fruits = ['banana', 'apple', 'pear']
for fruit in fruits:
    print ('Current fruit:', fruit)
print ("Good bye!")

Current fruit: banana
Current fruit: apple
Current fruit: pear
Good bye!


In [176]:
count = 0
while (count < 10):
    print ('The count is:', count)
    count = count + 1
print ("‘Good bye!’")

The count is: 0
The count is: 1
The count is: 2
The count is: 3
The count is: 4
The count is: 5
The count is: 6
The count is: 7
The count is: 8
The count is: 9
‘Good bye!’


In [177]:
count = 0
while (count < 10):
    print ('The count is:', count)
    count = count + 1

The count is: 0
The count is: 1
The count is: 2
The count is: 3
The count is: 4
The count is: 5
The count is: 6
The count is: 7
The count is: 8
The count is: 9


In [178]:
ty = (1,2,3)
min(ty)

1

In [179]:
max(ty)

3

In [181]:
yt = [8,9,6,2]
min(yt)

2

In [182]:
max(yt)

9

In [184]:
numbers = [10, 20, 30, 40]
numbers.pop()
print(numbers)

[10, 20, 30]


In [185]:
numbers = [10, 20, 30, 40]
numbers.pop(2)
print(numbers)

[10, 20, 40]


In [187]:
Numbers = [1,2,3,4,5,6,7]
evenList = []
oddList = []

for number in Numbers:
    if number % 2 ==0:
        evenList.append(number)
    else:
        oddList.append(number)
print(evenList)
print(oddList)

[2, 4, 6]
[1, 3, 5, 7]


In [ ]:
numbers = [1,2,3,4,5,6,7,8,9,10]
evenNumbers = []
oddNumbers = []

for number in numbers:
    if(number % 2 == 0):
        evenNumbers.append(number)
    else:
        oddNumbers.append(number)
print("The even numbers are: ", evenNumbers)
print("The odd numbers are: ", oddNumbers)

In [192]:
evenSum = 0
for i in evenList:
    evenSum += i
print(evenSum)

12


In [194]:
oddSum = 0
for i in oddList:
    oddSum += i
print(oddSum)

16


In [198]:
def convert_km_to_m (num_in_km):
    num_in_meter = num_in_km * 1000
    return(f"{num_in_km}km is {num_in_meter}m")
print(convert_km_to_m(19))

19km is 19000m


In [202]:
def celsius_to_fahrenheit_converter(celsius_degree):
    fahren_degree = round((celsius_degree * 9/5) + 32)
    return(f"{celsius_degree}c is {fahren_degree}f")
print(celsius_to_fahrenheit_converter(30))

30c is 86f


In [203]:
def calculate_area(length, breadth): #calculate_area is the identifier or function name and length, breadth are the parameters
    area = length * breadth #how to find the area
    return area

length = 2
breadth = 4

area = calculate_area(length,breadth) 

print(f"The area is {calculate_area(length,breadth) }")

The area is 8


In [204]:
def calculate_area(length, breadth): #calculate_area is the identifier or function name and length, breadth are the parameters
    area = length * breadth #how to find the area
    return (f"The area is {area}")
print(calculate_area(2,4))

The area is 8


In [222]:
def palindrome_checker(the_word):
    reversed_word = the_word[::-1]
    if reversed_word == the_word:
        return ("It's a palandrome")
    else:
        return ("It's not a palindrome")
print(palindrome_checker("madame"))

It's not a palindrome


In [223]:
def palindrome_checker(the_word):
    reversed_word = the_word[::-1]
    if reversed_word == the_word:
        return ("It's a palandrome")
    else:
        return ("It's not a palindrome")
print(palindrome_checker("madam"))

It's a palandrome


In [228]:
def palindrome_checker(the_word):
    reversed_word = the_word[::-1]
    if reversed_word == the_word:
        return "It's a palandrome"
    else:
        return "It's not a palindrome"
print(palindrome_checker("madam"))

It's a palandrome


In [224]:
def palindrome_checker(the_word):
    reversed_word = the_word[::-1]
    if reversed_word == the_word:
        print ("It's a palandrome")
    else:
        print ("It's not a palindrome")
print(palindrome_checker("madame"))

It's not a palindrome
None


In [227]:
def palindrome_checker(the_word):
    reversed_word = the_word[::-1]
    if reversed_word == the_word:
        print ("It's a palandrome")
    else:
        print ("It's not a palindrome")
return(palindrome_checker("madame"))

SyntaxError: 'return' outside function (1037980722.py, line 7)

So summary of the above, we need the return inside and we'd call the function outside with our desired argument for the parameter lol. 

Paradventure you use print and no return, it doesn't return anything so the value will be None after your print statement

In [231]:
def passChecker (password):
    if password == "pau@2D":
        return ("Correct password")
    else:
        return ("wrong password")
print(passChecker("pau2D"))

wrong password


In [238]:
def checkEmailValidity (email, at, dotCom):
    if at in email and dotCom in email:
        return("It is an email")
    else:
        return("It is not an email")

print(checkEmailValidity("charisoneyemiatgmail.com", "@", ".com"))

It is not an email


In [239]:
def checkEmailValidity (email, at, dotCom):
    if at in email and dotCom in email:
        return("It is an email")
    else:
        return("It is not an email")

print(checkEmailValidity("charisoneyemi@gmail.com", "@", ".com"))

It is an email


In [1]:
names = ['james', 'biodun', 'kaka', 'jumoke', 'bolaji']
ages = [20, 56, 76, 30, 23, 40]


for name, age in zip(names, ages):
    print(f"{name} {age}")

james 20
biodun 56
kaka 76
jumoke 30
bolaji 23


In [2]:
names = ['james', 'biodun', 'kaka', 'jumoke', 'bolaji']
ages = [20, 56, 76, 30, 23, 40]

file_handle = open("testing.txt", "w") #This opens (or creates if it doesn't exist) a file named output.txt in write mode ("w")
for name, age in zip(names, ages):#zip(names, ages)) pairs each element of names with the corresponding element of ages:
    file_handle.write(f"{name} {age}\n") #The file_handle.write() function is used to write a string of text into a file.
file_handle.close()#Properly closes the file to ensure all data is saved and resources are freed.



In [ ]:
names = ['james', 'biodun', 'kaka', 'jumoke', 'bolaji']
ages = [20, 56, 76, 30, 23, 40]
length = len(list)-1
tracker = 0

file_handle = open("output.txt", "w") #this is to write to a file named output.txt
for name, age in zip(names, ages):#take note of the fact that the var names are d/f as in name age list1 list2
    if tracker < length:
tracker = tracker + 1
    else:
        file_handle.write(name + " " + str(age) + "\n")

file_handle.close()

In [5]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5, 6, 7],
              [8, 9, 10, 11, 12, 13, 14]])

print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
print(a[0:30])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
print(a[0,3])

4


In [9]:
print(a[1,:])#ie all of row 1

[ 8  9 10 11 12 13 14]


In [11]:
print(a[:,2]) #ie all of column 2

[ 3 10]


In [12]:
print(a[0,3:6])

[4 5 6]


In [13]:
print(a[:,-1])

[ 7 14]


In [14]:
print(a[1,1:5])

[ 9 10 11 12]


In [17]:
print(a[0:1])

[[1 2 3 4 5 6 7]]


In [19]:
print(a[1,1])

9


In [21]:
print(a[0,:3])

[1 2 3]


In [22]:
print(a[0,:-3])

[1 2 3 4]


In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[1,4] = 34
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 34 13 14]]


In [29]:
print(a[0,:])#ie all of row 1


[1 2 3 4 5 6 7]


In [28]:
print(a[1:2])#ie all of row 1

[[ 8  9 10 11 34 13 14]]


In [30]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[1,4] = 34
print(a[1,4])
a[0,:] = [10,3,4,5,6,7,8]
print(a)

34
[[10  3  4  5  6  7  8]
 [ 8  9 10 11 34 13 14]]


In [31]:
s = np.array( [[[1,2]],[[3,4]], [[13,4]]])
print(s.shape)

(3, 1, 2)


In [32]:
a = np.array([1, 2, 3, 4])
print(a.shape)


(4,)


In [33]:
b = np.array([[1, 2], [3, 4]])
print(b.shape)


(2, 2)


In [34]:
c = np.array([[[1, 2]], [[3, 4]]])
print(c.shape)


(2, 1, 2)


In [35]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(d.shape)


(2, 2, 3)


In [36]:
e = np.array([[[[1, 2]]]])
print(e.shape)


(1, 1, 1, 2)


In [37]:
f = np.array([[[1]], [[2]], [[3]]])
print(f.shape)


(3, 1, 1)


In [38]:
g = np.array([[1, 2, 3]])
print(g.shape)


(1, 3)


In [42]:
g = np.array([[[[[1, 2, 3]]]]])
print(g.shape)


(1, 1, 1, 1, 3)


In [44]:
s = np.array( [[[1,2]],[[3,4]], [[13,4]]])
print(s.shape)
print(s.ndim)
s[0,:] = [379,777]
print(s)

(3, 1, 2)
3
[[[379 777]]

 [[  3   4]]

 [[ 13   4]]]


In [45]:
ranin = np.random.randint(0,4,size=(4,3))
print(ranin)

[[3 2 3]
 [1 2 1]
 [3 3 3]
 [2 1 2]]


In [46]:
s = np.array([1,2,3])
print(s+2)

[3 4 5]


In [47]:
s = np.array([1,2,3])
print(s*2)

[2 4 6]


# ALL ABOUT NUMPY

## NumPy Vectorization

Vectorised array operations refer to performing operations on arrays or elements in an array at once rather than looping through each element individually

How we would do it w/o using numpy

In [9]:
x = [1, 2, 3]
y = [4, 5, 6]

result = []
for i in range(len(x)):
    result.append(x[i] + y[i])
    
print(result)

[5, 7, 9]


How we would do it using numpy

In [10]:
x = [1, 2, 3]
y = [4, 5, 6]

result = np.array(x) + np.array(y)

print(result)


[5 7 9]


## CREATING A NUMPY ARRAY

Syntax

---
import numpy as np

---
a = np.array([])


## 1D NP ARRAY

In [2]:
import numpy as np
a = np.array([1,2,3,4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.ndim)

1


So the above is a 1D array and it has 4 elements that's why we see (4,)

## 2D NP ARRAY

In [13]:
a = np.array[[1,2]]

TypeError: 'builtin_function_or_method' object is not subscriptable

We had that code error because we didnt put our array in ()

In [15]:
a = np.array([[4,7]])
print(a.ndim)

2


Now this is a 2D array aand here's why


[4,7] this alone is a 1D

2D holds one or more 1D so inside it's [] we have one or more one D

For better viz of [[[4,7]]

[

    [4,7]
]
The shape is 1,2 no matter how many extra one d we have it we be x,2 because we alwyas have two columns for this particlar arry. See below

In [16]:
print(a.shape)

(1, 2)


In [17]:
a = np.array([[4,7],[2,5], [9,0]])
print(a.ndim)
print(a.shape)

2
(3, 2)


Shape is 3 rows 2 columns for better visualisation

[

    [4,7],
    [2,5],
    [9,0]

]

We have 3 rows and 2  columns

In [18]:
a = np.array([[1,3,4,5],[2,3,4,5],[4,5,6,7]])

In [19]:
print(a.shape) #It will be 3,4
print(a.ndim) #It will be 2

(3, 4)
2


In [21]:
s = np.array([[[1,4,5],[2,4,5],[5,6,7]],[[3,5,6],[1,4,5],[1,6,7]]])

Let's figure out what the shape and dimension would be

[
    [
        [1,4,5],
        [2,4,5],
        [5,6,7]
    ],
    [
        [3,5,6],
        [1,4,5],
        [1,6,7]
    ]
]


So we have 1D as [1,4,5]

We have 2 2Ds 
    [
        [1,4,5],
        [2,4,5],
        [5,6,7]
    ],
    [
        [3,5,6],
        [1,4,5],
        [1,6,7]
    ]
    
And they're wrapped in another [] so it is 3D, LET'S TEST IT

In [22]:
print(s.ndim)

3


In [23]:
print(s.shape)

(2, 3, 3)


The shape is (2,3,3) here's why

[[1,4,5],[2,4,5],[5,6,7]],
[[3,5,6],[1,4,5],[1,6,7]]


Looking at it this way we have how many 2D's we have 2 and each block has 3 rows and 3 columns. You can just pick one and look at [1,4,5],
                 [2,4,5],
                 [5,6,7]
                 
Hence the 2,3,3                 


The shape of the below will be 3,2,4 ie 3 blocks and each have 2 rows and 4 columns

In [41]:
# Reset redefined variables
del np.array
del list

# Then re-import NumPy
import numpy as np


AttributeError: 'module' object has no attribute 'array'

In [39]:
import numpy as np
a = np.array([[[2,2,3,4],[5,5,4,6]], [[5,5,4,3],[2,2,3,4]], [[2,2,3,4],[5,5,4,3]]])
print(a.shape)

TypeError: 'list' object is not callable

In [38]:
import numpy as np
a = np.array([
    [
        [1,2,3,4],
        [1,2,3,4]
    ],
    [
        [1,2,3,4],
        [1,2,3,4]
    ],
    [
        [1,2,3,4],
        [1,2,3,4]
    ]
])

TypeError: 'list' object is not callable

In [36]:
print(a.ndim)

2


In [4]:
a = "Hello, World!"
print(a[-1:6:-2])

!lo


In [16]:
a = "trichology"
print(a[1:1])