# ALL ABOUT NUMPY- Numerical Python

## NumPy Vectorization

Vectorised array operations refer to performing operations on arrays or elements in an array at once rather than looping through each element individually

How we would do it w/o using numpy

In [1]:
x = [1, 2, 3]
y = [4, 5, 6]

result = []
for i in range(len(x)):
    result.append(x[i] + y[i])
    
print(result)

[5, 7, 9]


In [2]:
import numpy as np

How we would do using numpy

In [3]:
x = [1, 2, 3]
y = [4, 5, 6]

result = np.array(x) + np.array(y)

print(result)


[5 7 9]


## CREATING A NUMPY ARRAY

Syntax

---
import numpy as np

---
a = np.array([])


## 1D NP ARRAY

In [5]:
import numpy as np
a = np.array([1,2,3,4])

In [6]:
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4]
(4,)
1


So the above is a 1D array and it has 4 elements that's why we see (4,)

## 2D NP ARRAY

In [7]:
b = np.array([[4,7]])
print(b.ndim)

2


Now this is a 2D array aand here's why

[4,7] this alone is a 1D

2D holds one or more 1D so inside it's [] we have one or more one D

For better viz of [[[4,7]]

[

[4,7]
] The shape is 1,2 no matter how many extra one d we have it we be x,2 because we alwyas have two columns for this particlar arry. See below

In [8]:
print(b.shape)

(1, 2)


In [3]:
c = np.array([[4,7],[2,5], [9,0]])
print(c.ndim)
print(c.shape)
cc = np.array([[[4,7],[2,5], [9,0]]])
print(cc.shape)

2
(3, 2)
(1, 3, 2)


Shape is 3 rows 2 columns for better visualisation

[

    [4,7],
    [2,5],
    [9,0]
]

We have 3 rows and 2 columns

In [11]:
d = np.array([[1,3,4,5],[2,3,4,5],[4,5,6,7]])
print(d.shape) #It will be 3,4
print(d.ndim) #It will be 2

(3, 4)
2


In [12]:
e = np.array([[[1,4,5],[2,4,5],[5,6,7]],[[3,5,6],[1,4,5],[1,6,7]]])

Let's figure out what the shape and dimension would be

[
    [
        [1,4,5],
        [2,4,5],
        [5,6,7]
    ],
    [
        [3,5,6],
        [1,4,5],
        [1,6,7]
    ]
]


So we have 1D as [1,4,5]

We have 2 2Ds 
    [
        [1,4,5],
        [2,4,5],
        [5,6,7]
    ],
    [
        [3,5,6],
        [1,4,5],
        [1,6,7]
    ]
    
And they're wrapped in another [] so it is 3D, LET'S TEST IT

# 3D NP ARRAY

In [14]:
print(e.ndim)
print(e.shape)

3
(2, 3, 3)


The shape is (2,3,3) here's why

[[1,4,5],[2,4,5],[5,6,7]], [[3,5,6],[1,4,5],[1,6,7]]

Looking at it this way we have how many 2D's we have 2 and each block has 3 rows and 3 columns. You can just pick one and look at [1,4,5], [2,4,5], [5,6,7]

Hence the 2,3,3

The shape of the below will be 3,2,4 ie 3 blocks and each have 2 rows and 4 columns

In [15]:
f = np.array([
    [
        [1,2,3,4],
        [1,2,3,4]
    ],
    [
        [1,2,3,4],
        [1,2,3,4]
    ],
    [
        [1,2,3,4],
        [1,2,3,4]
    ]
])

In [16]:
print(f.shape)

(3, 2, 4)


In [17]:
print(f.ndim)# 3d

3


Explanation of the x's is below

In [18]:
x = np.array([[1,2], [3,4]])
print(x.shape)

(2, 2)


In [19]:
x2 = np.array([[1,2], [3,4], [5,6]])
print(x2.shape)

(3, 2)


In [21]:
x3 = np.array([[[1,2], [3,4]]])
print(x3.shape)

(1, 2, 2)


In [22]:
x2 = np.array([[[1,2], [3,4], [5,6]]])
print(x2.shape)

(1, 3, 2)


# NOTE

The number of elements in the shape tuple corresponds to the number of dimensions (or axes) of the array. Let’s break it down further to make sure it’s crystal clear:

when it is 1d we see just  for example (4,)

when it's 2 d we see 2 elements for shape like (2,3)

but once it's 3d we see 3 elements for shape (2,3,4)

1D Array (One Dimension)
Shape: (N,)
Here, N is the number of elements in the array.
The shape has one value, because there's only one axis.



2D Array (Two Dimensions)
Shape: (M, N)
M is the number of rows.
N is the number of columns.
The shape has two values, because there are two axes (rows and columns).



3D Array (Three Dimensions)
Shape: (L, M, N)
L is the number of blocks (or outermost arrays).
M is the number of rows in each block.
N is the number of columns in each row.
The shape has three values, because there are three axes (blocks, rows, and columns).



# 4D Array (Four Dimensions)
Shape: (A, B, C, D)
First axis (A): Number of groups or outermost blocks.
Second axis (B): Number of sub-blocks in each group.
Third axis (C): Number of rows in each sub-block.
Fourth axis (D): Number of columns in each row.

In [23]:
import numpy as np

# 4D array
arr = np.array([
    [  # Group 1
        [  # Sub-block 1
            [1, 2, 3], 
            [4, 5, 6]
        ],
        [  # Sub-block 2
            [7, 8, 9], 
            [10, 11, 12]
        ]
    ],
    [  # Group 2
        [  # Sub-block 1
            [13, 14, 15], 
            [16, 17, 18]
        ],
        [  # Sub-block 2
            [19, 20, 21], 
            [22, 23, 24]
        ]
    ]
])

print(arr.shape)  # Output: (2, 2, 2, 3)


(2, 2, 2, 3)


So for this type we have 2 main blocks and each have 2 sub blocks with 2 rows and 3 columns


More examples below

In [24]:
arr1 = np.array([1, 2, 3, 4, 5])
# The shape is (5,)

In [25]:
print(arr1.shape)

(5,)


In [26]:
arr2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(arr2.shape) # This is 2d so we see 2 elements for the shape (3,2)

(3, 2)


In [28]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(arr3.shape)# This is a 3d we have 2 blocks and each has 2 rows and 3 columns so 2,2,3

(2, 2, 3)


In [30]:
arr4 = np.array([
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ],
    [
        [
            [9, 10],
            [11, 12]
        ],
        [
            [13, 14],
            [15, 16]
        ]
    ]
])
print(arr4.shape)# This is 4d so we have 2 main blocks, each have 2 sublocks with 2 rows and 2 columns so 2,2,2,2

(2, 2, 2, 2)


In [32]:
arr5 = np.array([
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ]
])
print(arr5.shape)# This is 4 d and we have 1 main block with 2 sublocks with 2r 2c ie 1,2,2,2

(1, 2, 2, 2)


In [34]:
arr6 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
])
print(arr6.shape)# This is 3d with 1 main block with 2 rows and 3 columns so 1,2,3

# this is wrong: This is 3d and we have 1 main block with 2 sub blocks with 2r, 3c so 1,2,2,3

(1, 2, 3)


# ACCESSING ELEMENTS IN NUMPY ARRAY - 1D

In [40]:
g = np.array([10, 20, 30, 40, 50])


In a 1D array, you can access elements by their index (just like in Python lists). Remember, NumPy follows 0-based indexing, meaning the first element is at index 0.

In [47]:
print(g[0]) # It will give the 1st element or index 0 is 10

10


In [48]:
print(g[4]) #It will give the 5th element or index 4 that is 50

50


In [49]:
print(g[-1])#last element

50


# SLICING ELEMENTS IN NUMPY ARRAY - 1D

In [50]:
print(g[0:3])# that is from the 0th index or 1st element to the 3rd index  or 4th element exluding it so 10, 20, 30

[10 20 30]


In [55]:
print(g[:3])  # Output: [10 20 30] same as above

[10 20 30]


In [56]:
print(g[2:])  # Output: [30 40 50] from the 3rd element to the end


[30 40 50]


# ACCESSING ELEMENTS IN NUMPY ARRAY - 2D

In [5]:
h = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In a 2D array, elements are accessed by two indices: the row index and the column index.


In [58]:
print(h[1,2])# That is the second column and the third element there --> 6

6


# ACCESSING ENTIRE ROWS IN NUMPY ARRAY - 2D

In [59]:
print(h[2]) #this will give us the third row ie 7 8 9

[7 8 9]


In [60]:
print(h[0]) #1 2 3

[1 2 3]


In [6]:
print(h[0,:]) #1 2 3
print(h[2,:]) #7 8 9

[1 2 3]
[7 8 9]


[0] and [0,:] are the same


Just know that when the comma , is on the left side ie left of the colon : then it is for row else column, look below

# ACCESSING ENTIRE COLUMNS IN NUMPY ARRAY - 2D

Just know that when the comma , is on the right side ie left of the colon : then it is for column look below

In [63]:
print(h[:,2]) # This is saying we want all the column at index 2 ie the 3rd column --> 3,6,9

[3 6 9]


In [64]:
print(h[:2, :2]) # learn later

[[1 2]
 [4 5]]


In [66]:
print(h[1:, 1:])# learn later just in case

[[5 6]
 [8 9]]


In [69]:
i = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(i)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [70]:
print(i[1,5]) # That is the row at index 1 and the element at index 5 -->13

13


In [71]:
print(i[0,:]) # That is [0] it's the same ie we want just the row at index 0 --> 1,2...7

[1 2 3 4 5 6 7]


In [72]:
print(i[:,1]) # That is we want the column at index 1 --> 2,9

[2 9]


In [73]:
print(i[0,1:6:2]) 
# That is we want the column at index 0 ---> 1  2  3  4  5  6  7
# then we want it to start at index 1 and end at index 6 excluding index 6---> 2,3,4,5,6
# then we want to skip 2 times --> 2,4,6

[2 4 6]


In [75]:
j = np.array([[[1,2,3],[2,3,4]],[[4,5,6],[1,6,1]]])
print(j.shape)# this is 3d and we have 2 block with 2 rows and 3 columns so 2,2,3
print(j.ndim)


(2, 2, 3)
3


In [84]:
print(j[0,0,:])
# That is since it's 3d we want the block at index 0 then in that block we want to row at index 0 and then : all of it



[1 2 3]


In [78]:
k = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(k[1, 2])
#That is we want the row at index 1 and the element at index 2 --> 6

6


In [80]:
arr3d = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]]])
print(arr3d[1, 0, :])
print(arr3d.shape)
#This is a 3d with shape 2,2,2 and we want the block at the 1st index then the row at the 0th index then all of it--> 50,60


[50 60]
(2, 2, 2)


In [83]:
l = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(l[:, 1])#We want the column at index 1-->  2,5,8

[2 5 8]


# Change data in an Array

In [85]:
m = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# Thid is a 2d array
print(m.ndim)

2


In [87]:
print(m[1,4]) #So this gives us the row at index 1 and the element at index 4 there

12


In [88]:
#So to change it, we state that particular element then assign it to the new value we want
m[1,4] = 24
print(m)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 24 13 14]]


In [90]:
print(m[0:,])#please look below for explanation

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 24 13 14]]


I thought that m[0:,] will give us the whole of the row at index 0 and that it's the same as m[0] but 

m[0:,] is different from m[0,:]


m[0,:] the one with the comma before the column is what will give us the whole first row

Once the comma comes after the colon ie 0:, it means "from row index 0 onwards." We'd try it with a 2d of shape 4,2. Please look below the row below

In [92]:
print(m[0,:])

[1 2 3 4 5 6 7]


In [94]:
import numpy as np
n = np.array[[1,2],[3,4],[5,6],[7,8]]
print(n.ndim)
print(n.shape)

TypeError: 'builtin_function_or_method' object is not subscriptable

We have to stop making this error. When doing a numpy array, it's meant to be np.array()

Don't forget to use your bracket ()

In [95]:
import numpy as np
n = np.array([[1,2],[3,4],[5,6],[7,8]])
print(n.ndim)
print(n.shape)

2
(4, 2)


So let's access from the second row to the end

In [97]:
print(n[1:,]) # So it will print all rows onwards from the 1st index

[[3 4]
 [5 6]
 [7 8]]


In [99]:
o = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(o[0,:])

[1 2 3 4 5 6 7]


In [100]:
print(o)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [101]:
p =  np.array( [[[1,2]],[[3,4]], [[13,4]]])

So let's understand what kind of array this is like the dimension

[
    [
        [1,2]
    ],
[
    [
        [3,4]
    ],
[
    [
        [13,4]
    ]
]


So this is a 3d array with 3 subblocks, which have 1 row and 2 columns
So the shape is 3,1,2

In [103]:
print(p.shape)
print(p.ndim)

(3, 1, 2)
3


In [104]:
print(p[0,0:]) #So this is the block at index 0 and in that block, we want all rows from the 1st index 
#so since we have just 1 row there at index 0 it just prints that --> [1,2]

[[1 2]]


So let's test it with an array of shape 3,3,2 and get from the 1st row downward of the 3rd block

In [105]:
q = np.array(
[
    [
        [1,2],
        [3,4],
        [4,6]
    ],
    [
        [7,8],
        [9,10],
        [11,12]
    ],
    [
        [13,14],
        [15,16],
        [17,18]
    ]
]
)

print(q.shape)

(3, 3, 2)


In [108]:
print(q[2,1:]) # This prints the block at index 2 and prints all rows starting from the row at index 1 downwards

[[15 16]
 [17 18]]


# Initializing Numpy Arrays


### ZEROS --> np.zeros((the shape))
The syntax is np.zeros, we usually use np.array but now  since we want zero's we do np.zeros and we specify the shape

In [111]:
r = np.zeros(2,3)#so this creates a numpy array of zeros with the shape 2,3
print(r)

TypeError: Cannot interpret '3' as a data type

So this doesn't work because we're meant to put out shape () into the np.zeros()

In [112]:
r = np.zeros((2,3))#so this creates a numpy array of zeros with the shape 2,3
print(r)

[[0. 0. 0.]
 [0. 0. 0.]]


### ONES --> np.ones((the shape))

In [138]:
r1 = np.ones((2,3)) # Just like ZERO's, ONE's generates a numpy array of 1's you just have to specify the shape
print(r1)

[[1. 1. 1.]
 [1. 1. 1.]]


### FULL --> np.full((the shape), the value we want to fill it with)

It takes two values: the shape and then the element we want in it


In [140]:
r2 = np.full((2,3), 70)
print(r2) #so it gives a 2 by 3 matrix with full of values 70

[[70 70 70]
 [70 70 70]]


In [144]:
r3 = np.full((4,3,2), 50) 
print(r3)
print(r3.ndim)
print(r3.shape) #This is a 3d array with 4 blocks which have 3 rows and 2 columns

[[[50 50]
  [50 50]
  [50 50]]

 [[50 50]
  [50 50]
  [50 50]]

 [[50 50]
  [50 50]
  [50 50]]

 [[50 50]
  [50 50]
  [50 50]]]
3
(4, 3, 2)


### Understanding np.random

### np.random.randint(values to generate from)
### np.random.randint(values to generate from, (the shape)) --> for array of integers
### np.random.rand(the shape) --> this one is (0,1]


np.random: This is the module that contains various random number generation functions.
np.random.rand: Uniform random floats in the range [0, 1) ie inclusive of zeros exclusive of 1
np.random.randint: Random integers within a specified range.

So if we want to do .rand or .randint, we the specify the shape () in the .rand() or .randint()

In [7]:
s = np.random.rand(3,4) # This generates random numbers of the shape 3 rows 4 cols 
#it does not generates a random number between 3 and 4
print(s)

[[0.1827114  0.10627763 0.18064379 0.01358386]
 [0.65255556 0.2605007  0.15214316 0.74618357]
 [0.45537594 0.22824672 0.69664149 0.93796705]]


So on a normal day we do this bracket stuff

npArr = np.arr([1,2])

For zeros we use np.zeros() and in the () we put in the shape in () so np.zeros((2,3))

But for random.rand or .randint we have to just use one ()

So random.rand takes two values x and y and it generates random numbers between 0 and 1 exclusive of 1 of the shape x rows y cols 
But random.randint will generate a number between x and y exclusive of y

So np.random.randint(2,4) will give you either 2 or 3 because it's between 2 and 4 exclusive of 4
but np.random.rand(2,4) will give floats in the range [0, 1) ie inclusive of zeros exclusive of 1

For the np.random.randint, if we want an array of random integers, we would have to specify the particular shape


Recap of Key Differences:
np.zeros((2, 3)): Takes a single argument: a tuple representing the shape (rows, columns).

np.random.rand(2, 3): Takes multiple arguments (e.g., 2 and 3), representing the shape of the array.
Generates random floats in the range [0, 1).

np.random.randint(1, 10, size=(2, 3)):

Takes the range (1 to 10, exclusive of 10) and uses the size argument to specify the shape of the array (e.g., (2, 3)).

Look below

In [129]:
s2 = np.random.randint(3,8)
print(s2)

5


In [130]:
s3 = np.random.rand(2,4)
print(s3)

[[0.33090259 0.84640448 0.36333549 0.8307395 ]
 [0.0681076  0.06413726 0.73505279 0.39550341]]


In [134]:
s4 = np.random.randint(0,4, size = (4,3)) # So this is going to give a random integer between 0 and 4 exclusive of 4 
# and the shape is going to be 4,3 ie 4 rows 3 columns
print(s4)

[[3 1 3]
 [2 1 1]
 [2 0 3]
 [0 2 3]]


# Numpy  Packages

np (NumPy package) 

---------
random (module within NumPy)

---------
randint (function within the random module) 

# Element-wise addition

In [135]:
t = np.array( [2,3,4,5,6,7])
answer = t + 2
print(answer)

[4 5 6 7 8 9]


# Linear Algebra

In [136]:
u = np.ones((2,3)) # Just like we have zeros
print(u)

[[1. 1. 1.]
 [1. 1. 1.]]


### MATMUL

Our matrix rule states that if we have to multipy a matrix, the columns of the first have to be same as the rows of the second (like same number)

Then our resulting array using matmul will be the row of the first and the column of the second

look below

In [146]:
npOne = np.ones((3,2))
print(npOne) #here the shape is 3 rows and 2 columns so if we're multiplying the other array has to have 2 rows

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [149]:
#npRandomInt = np.random.randint((2,9), size = (2,4)) #This is an array of 2 rows 3 columns with values [2,9) ie 9 exclusive
# This is wrong because the values of lower and upper bound 2,9 shouldn't be in () look below

In [153]:
npRandomInt = np.random.randint(2,9, size = (2,4)) #so it takes in 3 values 

In [154]:
print(npRandomInt)

[[6 7 6 7]
 [8 3 8 8]]


In [155]:
multiplication1 = np.matmul(npOne, npRandomInt)
print(multiplication1)

[[14. 10. 14. 15.]
 [14. 10. 14. 15.]
 [14. 10. 14. 15.]]


### SUM and axis


The axis argument controls whether you are performing the operation along the rows or columns of the array. 


0 is for columns 

--

1 is for rows


-- 

So sum is np.sum()

It takes two parameters (the variable that holds the array and the axis we want)


In [156]:
v = np.array([[1,2,3],[4,5,6]])
print(v.shape)
print(np.sum(v,axis=0))
print(np.sum(v,axis=1))

(2, 3)
[5 7 9]
[ 6 15]


So axis = 0 sums column by column

--

While axis = 1 sums row by row

--

axis 0 --> 1+4, 2+5, 3+6 = 5,7,9

--

axis 1 --> 1+2+3, 4+5+6 = 6,15

### Getting data from txt file ---> npgenfromtxt()

In [158]:
sc = np.genfromtxt("scores.txt", delimiter=',')
s = sc > 10
print(s)


[[False False False False False False False]
 [ True  True  True False False  True  True]
 [False False False False  True  True  True]]


s = sc > 10:

This performs a comparison operation.
Each element in sc is compared to 10, and the result is a Boolean array of the same shape as sc.
If an element in sc is greater than 10, the corresponding element in s is True; otherwise, it is False.
For the above example, the comparison works like this:

For the first row: [5, 8, 12, 6, 3, 10, 7], values greater than 10 are 12, so the result is: [False, False, True, False, False, False, False]
For the second row: [14, 20, 15, 8, 9, 13, 17], values greater than 10 are 14, 20, 15, 13, 17, so the result is: [True, True, True, False, False, True, True]
For the third row: [4, 6, 2, 10, 11, 18, 25], values greater than 10 are 11, 18, 25, so the result is: [False, False, False, False, True, True, True]

In [159]:
print(sc)

[[ 1.  2.  3.  4.  5.  6.  7.]
 [12. 34. 67.  8.  0. 12. 34.]
 [ 3.  4.  6.  7. 89. 12. 12.]]


In [160]:
print(sc[s]) #That is elements greater than 10

[12. 34. 67. 12. 34. 89. 12. 12.]


### Getting average - np.average()

In [161]:
our_numbers = np.genfromtxt('scores.txt', delimiter = ',')

average_numbers = np.average(our_numbers)

In [162]:
print(average_numbers)

15.619047619047619


### Getting max - np.max()

In [165]:
our_max = np.max(our_numbers)
print(our_max)

89.0


### Getting min - np.min()

In [166]:
our_min = np.min(our_numbers)
print(our_min)

0.0


### Get the total number of students who had 30 and above --> np.sum()

In [168]:
greater_than_30 = our_numbers > 30

print(greater_than_30) #So this doesn't give exactly what we want so check the next code block

[[False False False False False False False]
 [False  True  True False False False  True]
 [False False False False  True False False]]


In [169]:
greater_than_30 = our_numbers >= 30
count = np.sum(greater_than_30)
print(count)

4


In [170]:
sc = np.genfromtxt("scores.txt",delimiter=',')
thirty_and_above = sc >=30
number = sc[thirty_and_above]
print(len(number))

4


So these two codes above are different solutions to the problem but I prefer the 1st one the np.sum

In [171]:
jeff_salary = [2700,3000,3000]
nick_salary = [2600,2800,2800]
tom_salary = [2300,2500,2500] 
base_salary = np.array([jeff_salary, nick_salary, tom_salary])
print(base_salary)

[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]]


In [172]:
jeff_bonus = [500,400,400]
nick_bonus = [600,300,400]
tom_bonus = [200,500,400]
bonus = np.array([jeff_bonus, nick_bonus, 
tom_bonus])

So we have the base salary and we also have the bonus what we want to do is to add the base salary to the bonus to see the salary and bonus together

In [173]:
salary_and_bonus = base_salary + bonus
print(salary_and_bonus)

[[3200 3400 3400]
 [3200 3100 3200]
 [2500 3000 2900]]


In [175]:
max_salary = np.max(salary_and_bonus)
print(max_salary)

3400


In [176]:
min_salary = np.min(salary_and_bonus)
print(min_salary)

2500


NumPy can also find the maximum value of 
an array along a given axis.

In [180]:
print(np.amax(salary_and_bonus, axis = 1)) # that is the highest value per row. Remember row is 1

[3400 3200 3000]


In [181]:
print(np.amax(salary_and_bonus, axis = 0)) # that is highest value per column. Remember column is 0

[3200 3400 3400]


In [182]:
t = np.array([[[[1,2,3],[4,5,6]],[[5,6,7],[3,4,5]]],[[[1,2,3],[4,5,6]],[[5,6,
7],[3,4,5]]]])

The below is wrong please check the next block of markdown but go through this to see the error after seeing the right code

So let's discover the shape and dimension of this
[
    [
        [
            [1,2,3],
            [4,5,6]
        ]
        
        [
            [5,6,7],
            [3,4,5]
        ]
        [
            [1,2,3],
            [4,5,6]
        ]
        [
            [5,6,7],
            [3,4,5]
        ]
    ]
]


So we have a 4D

The shape is: We have 1 block of 3d, we have 4 sub blocks of 2d which has 2 rows 4 columns
So it the shpae should be (1,4,2,4)

[

    [
        [[1,2,3],[4,5,6]],
        [[5,6,7],[3,4,5]]
    ],
    [
        [[1,2,3],[4,5,6]],
        [[5,6,7],[3,4,5]]
    ]

]


So this is 

In [8]:
v = np.array([[1,2,3],[4,5,6]])
print(v.shape)
print(np.sum(v,axis=0))
print(np.sum(v,axis=1))

(2, 3)
[5 7 9]
[ 6 15]


1 2 3
4 5 6

In [ ]:
u = np.array([[1,2,3],[4,5,6]])
print(u.shape)
print(np.sum(u,axis=0))
print(np.sum(u,axis=1))

In [11]:
w =np.array ([[[1,2,3],[4,5,6]],[[5,6,7],[3,4,5]]])
print(w.shape)

(2, 2, 3)


In [12]:
wSum = np.sum(w, axis=2)
print(wSum)

[[ 6 15]
 [18 12]]


Step-by-step calculation:

Block 1:
Row 1: 1 + 2 + 3 = 6

Row 2: 4 + 5 + 6 = 15


Block 2:
Row 1: 5 + 6 + 7 = 18

Row 2: 3 + 4 + 5 = 12

In [13]:
wSum = np.sum(w, axis=1)
print(wSum)

[[ 5  7  9]
 [ 8 10 12]]


In [17]:
wSum = np.sum(w, axis=0)
print(w)
print("    ")

print("    ")

print(wSum)

[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [3 4 5]]]
    
    
[[ 6  8 10]
 [ 7  9 11]]
